### ISSUE TITLE
Corrupt Heap - send_base64_encode_data

### ISSUE THREAD

**Issue by Xyw25** [mobizt/ESP32-Mail-Client#10]
Hello there again,

First most thanks for creating this great thing.

Using version 1.0.5

The current issue is that when I am trying to create a text file attachment with over a certain size it will always result in a "CORRUPT HEAP: multi_heap.c:432 detected at 0x78416954"

![Error_message](https://user-images.githubusercontent.com/22323295/57478069-b0eb7480-72a2-11e9-9c21-41359baa1eca.png)

I added a few minor callbacks within the method:
`bool ESP32_MailClient::sendMail(HTTPClientESP32Ex &http, SMTPData &smtpData)`

So that I can better detect where the issue is, so far I am sure that it is within :
`void ESP32_MailClient::send_base64_encode_data(WiFiClient *tcp, const unsigned char *src, size_t len)`

Inside ESP32_MailClient.cpp at line 3083 we have the following:
`  delete[] buf;`

I've modifed the Send Email example and included the String over there and tested it, it will always restart because of the Corrupt Heap Error

Please don't judge the code (and I hope the issue isn't from my part).

```
  String data1 = String("NUMBER  DATE    START   DURATION  EVENT       TEMP  UNIT  \n100/00/201612:00:00 AM   --   POWER ON 16C200/00/201612:00:00 AM   --   POWER ON 16C300/00/201612:00:00 AM   --   POWER ON 16C400/00/201612:00:00 AM   --   POWER ON 16C500/00/201612:00:00 AM   --   POWER ON 16C600/00/201612:00:00 AM   --   POWER ON 16C700/00/201612:00:00 AM   --   POWER ON 16C800/00/201612:00:00 AM   --   POWER ON 16");

  char fileContent1[data1.length()];
  data1.toCharArray(fileContent1, data1.length());

  uint8_t byteArray1[11000];

  for (int i = 0; i < data1.length(); i++)
  {
    byteArray1[i] = uint8_t(fileContent1[i]);
  }

  smtpData.addAttachData("test_atasament_error.txt", "text/txt", byteArray1, data1.length());
```

**Comment by mobizt** [comment]
You assign incorrect **size** parameter which must be the size in byte of **data** parameter.
Becase this size parameter will be used as part of pointer in send_base64_encode_data.

```C++
addAttachData(const String &fileName, const String &mimeType, uint8_t *data, uint16_t size)
```
This is the correct use
```C++
smtpData.addAttachData("test_atasament_error.txt", "text/txt", byteArray1, sizeof byteArray1);
```
Based on your current data, you need to increase stack size to about **17100**.
