### ISSUE TITLE
smtpData.addAttachFile doesn't work with esp32-cam module

### ISSUE THREAD

**Issue by Vicentetomas** [mobizt/ESP32-Mail-Client#11]

**Comment by Vicentetomas** [comment]
Hello, The email is sent perfectly but without any attachment. I  put the number of the file and path but I never receive the email with it. I hope you can help me.
Nice post

**Comment by mobizt** [comment]
Please post your sketch here, serial print debug message, I can't help if you provide brief information like this.

**Comment by Vicentetomas** [comment]
Thank you for your quick answer
From your skectch I changed  the library sd.h to -->SD_MMC.h and seems it detects the micro sd. Before(with the sd.h). I've always received the message: "SD Card Monting Failed".
But changing the library from SD to SD_mmc now, works and mount the card,.
I double checked that the 2 files are created in the microS,  but I never receive the attachment with the email.
Thank you for your help
This is the debug message:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8

Connecting to AP.....
WiFi connected.
IP address: 
192.168.1.8

Mounting SD Card...
Preparing attach file...

Sending email...
Connecting to SMTP server...
SMTP server connected, wait for response...
Identification...
Identification...
Authentication...
Sign in...
Sending Email header...
Sending Email body...
Sending attacments...
Finalize...
Finished
Email sent successfully
----------------

THIS is the stektch:


/*
 * Created by K. Suwatchai (Mobizt)
 * 
 * Email: k_suwatchai@hotmail.com
 * 
 * Github: https://github.com/mobizt
 * 
 * Copyright (c) 2019 mobizt
 *
*/


//Required HTTPClientESP32Ex library, can be installed from https : //github.com/mobizt/HTTPClientESP32Ex

//To use send Email for Gmail, less secure app option should be enabled. https://myaccount.google.com/lesssecureapps?pli=1

//To receive Email for Gmail, IMAP option should be enabled. https://support.google.com/mail/answer/7126229?hl=en


#include <Arduino.h>
#include "ESP32_MailClient.h"
#include "SD_MMC.h"

//For demo only
#include "image.h"

#define WIFI_SSID "MYWIFI"
#define WIFI_PASSWORD "MYPASSWORD"

//WiFi or HTTP client for internet connection
HTTPClientESP32Ex http;

//The Email Sending data object contains config and data to send
SMTPData smtpData;

//Callback function to get the Email sending status
void sendCallback(SendStatus info);

void setup()
{

  Serial.begin(115200);
  Serial.println();

  Serial.print("Connecting to AP");

  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(200);
  }

  Serial.println("");
  Serial.println("WiFi connected.");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  Serial.println();


  Serial.println("Mounting SD Card...");

  if (SD_MMC.begin())
  {

    Serial.println("Preparing attach file...");

    File file = SD_MMC.open("/text_file.txt", FILE_WRITE);
    file.print("Hello World!\r\nHello World!");
    file.close();

    file = SD_MMC.open("/binary_file.dat", FILE_WRITE);

    static uint8_t buf[512];

    buf[0] = 'H';
    buf[1] = 'E';
    buf[2] = 'A';
    buf[3] = 'D';
    file.write(buf, 4);

    size_t i;
    memset(buf, 0xff, 512);
    for (i = 0; i < 2048; i++)
    {
      file.write(buf, 512);
    }

    buf[0] = 'T';
    buf[1] = 'A';
    buf[2] = 'I';
    buf[3] = 'L';
    file.write(buf, 4);

    file.close();
  }
  else
  {
    Serial.println("SD Card Monting Failed");
  }

  Serial.println();


  Serial.println("Sending email...");

  //Set the Email host, port, account and password
  smtpData.setLogin("smtp.gmail.com", 465, "myemail@gmail.com", "mypassword");

  //Set the sender name and Email
  smtpData.setSender("ESP32", "myemail@gmail.com");

  //Set Email priority or importance High, Normal, Low or 1 to 5 (1 is highest)
  smtpData.setPriority("High");

  //Set the subject
  smtpData.setSubject("ESP32 SMTP Mail Sending Test");

  //Set the message - normal text or html format
  smtpData.setMessage("<div style=\"color:#ff0000;font-size:20px;\">Hello World! - From ESP32</div>", true);

  //Add recipients, can add more than one recipient
  smtpData.addRecipient("vicentetomasgarciaperez@gmail.com");



  //Add attachments, can add the file or binary data from flash memory, file in SD card
  //Data from internal memory
 // smtpData.addAttachData("firebase_logo.png", "image/png", (uint8_t *)dummyImageData, sizeof dummyImageData);

  //Add attach files from SD card
  //Comment these two lines, if no SD card connected
  //Two files that previousely created.
  smtpData.addAttachFile("/binary_file.dat");
  smtpData.addAttachFile("/text_file.txt");


  smtpData.setSendCallback(sendCallback);

  //Start sending Email, can be set callback function to track the status
  if (!MailClient.sendMail(http, smtpData))
    Serial.println("Error sending Email, " + MailClient.smtpErrorReason());

  //Clear all data from Email object to free memory
  smtpData.empty();

}

void loop()
{
}

//Callback function to get the Email sending status
void sendCallback(SendStatus msg)
{
  //Print the current status
  Serial.println(msg.info());

  //Do something when complete
  if (msg.success())
  {
    Serial.println("----------------");
  }
}

**Comment by mobizt** [comment]
This Mail client library used SD library internally instead of SD MMC library. The use of SD MMC library in sketch outside Mail client library was not affected the internal operatoion unless may be ambiguous because they are subclasses of the same FS class.

If your media is not mmc or just microSD, you can use Arduino SD library. I recommend to test your connection to work with SD library and test read/write some file.

Here is some [example](https://randomnerdtutorials.com/esp32-data-logging-temperature-to-microsd-card/) that use SD lib with microSD card.

**Comment by Vicentetomas** [comment]
Thank you for your answer. I cannot make it works.
I've tried to put the SD.begin(x). with x= 4,2,12,13
 Is it possible to redefine the pins of the SDl library?.
The module I'm using is [ESP32CAM](https://randomnerdtutorials.com/esp32-cam-video-streaming-face-recognition-arduino-ide/) and this is the squematic :

	* GPIO 14: CLK
	* 
GPIO 15: CMD
	* 
GPIO 2: Data 0
	* 
GPIO 4: Data 1 (also connected to the on-board LED)
	* 
GPIO 12: Data 2
	* 
GPIO 13: Data 3

**Comment by Vicentetomas** [comment]
Yesssss! I've already found the solution.
Must be defined 
  SPI.begin(14, 2, 15, 13);
SD.begin(13).

Thank you very much for your time!!
