### ISSUE TITLE
SPIFFS instead of SD?

### ISSUE THREAD

**Issue by clydde** [mobizt/ESP32-Mail-Client#13]
Would it be easy to use SPIFFS instead of SD?
 Do you plan to implement the option?

Thankyou!

**Comment by mobizt** [comment]
Not support and may be the future update

**Comment by mobizt** [comment]
The library was updated and now supports SPIFFS.

**Comment by clydde** [comment]
uahohhh!UUu!!!! its fantastic!!!! 

What do you mean by "smille file"? 

Thankyou!!!

**Comment by mobizt** [comment]
I mean small size attachment. From my test, SPIFF is relatively slow to download/upload the attahments as compare to SD.

**Comment by clydde** [comment]
Hi, some time ago I found that the implementation of SPIFFS reading from the ArduinoJson library was much slower than if it was made from SD. I told Bblanchon of ArduinoJson that he was so kind to find a solution, it was about using the buffer when reading the json, I attach the link in case it can help to improve the speed with SPIFFS.

https://github.com/bblanchon/ArduinoStreamUtils

**Comment by mobizt** [comment]
Thank you so much for information about stream library. I will test it and may adapt to use in the future update.
