### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by vincent-bruel** [mobizt/ESP32-Mail-Client#14]
Hello,
When compiling with Arduino IDE 1.8.9, i have the error:
ESP32_MailClient.cpp:1878:9: error: 'transform' is not a member of 'std'
         std::transform(tmp.begin(), tmp.end(), tmp.begin(), ::tolower);
         ^
ESP32-Mail-Client-master\src\ESP32_MailClient.cpp:2047:13: error: 'sort' is not a member of 'std'
             std::sort(imapData._msgNum.begin(), imapData._msgNum.end(), compFunc);
             ^

Am i missing something ?

**Comment by mobizt** [comment]
Make sure you installed latest  ESP32 Arduino Core SDK, install it from **Boards Manager** by search esp32 and install v 1.0.2.

Now you should have this file 

**C:\Users\YOUR_NAME\AppData\Local\Arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\bits\stl_algo.h**

Compile your sketch again, if still got errors, at [line 44 of ESP32_MailClient.h](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.h#L44), add  `#include <algorithm>`

**Comment by vincent-bruel** [comment]
Thank you.
