### ISSUE TITLE
Support Ethernet

### ISSUE THREAD

**Issue by BrenuDev** [mobizt/ESP32-Mail-Client#16]
Hi,

Is it possible to add support for Ethernet?
I have a product which uses Ethernet and WiFi.

**Comment by mobizt** [comment]
Ethernet shield on ESP32? No this library based on WiFi.

**Comment by BrenuDev** [comment]
The ESP32 has native Ethernet support. My PCB design uses the LAN8720 PHY LAN chip. It is fully working.
You can just use the default ETH Arduino library.
![image](https://user-images.githubusercontent.com/8317833/62619515-45ec2100-b917-11e9-861c-b23a7e5d69db.png)
Just like that
EDIT:
The ETH LAN8720 demo also uses the WiFiClient class to communicate.

**Comment by mobizt** [comment]
It should build the ethernet client to support SSL/TLS as I know it's not implemented

I found one [here](https://github.com/telliottosceola/Ethernet_Test/tree/master/src) but never try it.  Look like it's WiFiClientSecure porting to work with mbedTLS and lwip.

Then no ethernet support at this time.
