### ISSUE TITLE
Crash Latest Version

### ISSUE THREAD

**Issue by BrenuDev** [mobizt/ESP32-Mail-Client#17]
Hi

As this is the proper repo for my issue
I've posted it here first => https://github.com/mobizt/HTTPClientESP32Ex/issues/2
![image](https://user-images.githubusercontent.com/8317833/62781067-681ca500-bab7-11e9-931f-077974b37b84.png)
With the latest version it crashes.
When i revert back to V1.2.0 it works just fine.
Please Check :)

**Comment by mobizt** [comment]
Look like debug callback related issue, please stay at 1.2.0, I will check the possibility of errors and inform you soon.

**Comment by mobizt** [comment]
I fixed the error and update to v1.2.2.
