### ISSUE TITLE
How to add "Date:" and "Message-ID:" to email header?

### ISSUE THREAD

**Issue by Koepel** [mobizt/ESP32-Mail-Client#18]
The spam filter complains that the email has no "Date:" and "Message-ID:" field.
Is it possible to add those header fields when sending an email ?

I used the example "Send_email.ino" and I removed the SD part, because I do not use SD or SPIFFS at the moment.
Is it possible to add other custom headers ?

**Comment by mobizt** [comment]
The answer is yes from the smtp standard but from my implementation these data will be overwritten by server.

Then these are not implemented by this library.

If you have success case for setting date and message-id using smtp's data command please share.

**Comment by Koepel** [comment]
I am using the SMTP server of my Internet Provider and sending it to a GMail account. Looking at the received email, the spam filter raises the X-Spam-Score from 1.603 to 3.46 with those two missing fields in the header. There is also X-Amavis-Alert for the missing Date. 
The Date was added by someone and Google adds a Message-Id.

I have done a quick and dirty test, but it is just a prove of concept, using buffers like that is only for a test.

The time is retrieved from a NTP server using the [SimpleTime.ino](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Time/SimpleTime/SimpleTime.ino) sketch.
In the code below, the "example.com" should be replaced with the last part of the sender email, but any unique number will do for the Message-ID.
I'm using the "Subject" field to add the other fields. The call to `smtpData.setSubject()` was replaced with the new function `multiHeader()`.

```
void multiHeader()
{
  // ----------------------------------------
  // Create a world-wide unique Message-ID
  // ----------------------------------------
  // The time should be running.
  
  struct tm timeinfo;
  getLocalTime( &timeinfo);
  time_t t = mktime( &timeinfo);                                

  // Create some random text, not needed, just for fun
  static char random_buf[16];
  for( int i=0; i<15; i++)
  {
    random_buf[i] = random( 'A', ('Z' + 1));
  }
  random_buf[15] = '\0';

  static char mid_buf[80];
  sprintf( mid_buf, "Message-ID: <%lu%s@example.com>", (unsigned long) t, random_buf); // no extra \r\n at the very end

  // ----------------------------------------
  // Create a Date field
  // ----------------------------------------
  // Using the same timeinfo struct that was already filled with data
  static char date_buf[64];
  strftime( date_buf, sizeof(date_buf), "Date: %a, %d %b %Y %H:%M:%S %z\r\n", &timeinfo);

  // ----------------------------------------
  // Create the extended header.
  // ----------------------------------------
  // Start with the subject

  static char buff[160];
  strcpy( buff, "ESP32 SMTP Mail Sending Test\r\n");
  strcat( buff, date_buf);
  strcat( buff, mid_buf);

  smtpData.setSubject( buff);
}
```

**Comment by mobizt** [comment]
I can't accept this settings as a standard parameters for this library because Message-ID is not what you think. It is the uri that specified the resouce or message in mail store for reference which has its format described in standard and also Date format. These field should handle by mail server.

I will add some function to add custom data properties instead. May be on the future update or you mad a custom version yourself.

**Comment by Koepel** [comment]
I have been reading about standards, proposed standards and recommendations. I think that the mail-sending-client "should" add the Message-ID and the Date. The mail server "may" add them if they are missing. 
The Date format is specified, and I used the right format. 
As far as I can tell, the Message-ID is a unique identifier and it does not matter what it is. Although it is often a combination of the time, then some random, then a domain.

Adding those fields does lower the spam score.
Looking at new created messages (not a reply) in the SENT folder in Thunderbird, they have those fields.

**Comment by mobizt** [comment]
Ok you're right.  Mail client can set any custom header then I will add this feature to the next update.

**Comment by mobizt** [comment]
Now I update the library to v2.0.0.

These are some changes from previouse version.

- Able to add custom header field.
- No more HTTPClientESP32Ex dependency.
- Not required http client in `sendMail` and `readMail` functions, just only pass the smtpData or imapData to the function.

See examples for usage.

**Comment by Koepel** [comment]
Thank you! That is a nice improvement.
