### ISSUE TITLE
cyclic check for new e-mails does not work

### ISSUE THREAD

**Issue by piti1** [mobizt/ESP32-Mail-Client#2]
I took the receive-example and put the e-mail receiving part from the setup routine into the loop with a time cycle of 60000 ms which should check every 60 seconds for e-mails. After reboot always just the first cycle works. All others are bringing error messages:
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, 
STATUS: failed

**Comment by mobizt** [comment]
Can you share the sketch for the loop and I will investigate into it to find the causes?

**Comment by piti1** [comment]
void vCheck_EMails(void)
{
  if(currentMillis - previousMillis_Check > interval_Check)   
    {
    
    imapData.setLogin("imap.gmail.com", 993, "xxxx@gmail.com", "xxxx");
    imapData.setFolder("xxxx");
    imapData.setFechUID("");
    imapData.setSearchCriteria("UID SEARCH ALL");
  
    imapData.setSaveFilePath("/email_data");
    imapData.setDownloadAttachment(false);
    imapData.setHTMLMessage(true);
    imapData.setTextMessage(true);
    imapData.saveHTMLMessage(false, false);
    imapData.saveTextMessage(false, false);
    imapData.setHeaderOnly(true);
    imapData.setSearchLimit(20);
    imapData.setRecentSort(true);
    imapData.setMessageBufferSize(2000);  //200
    imapData.setAttachmentSizeLimit(1024 * 1024 * 5);
    imapData.setReadCallback(readCallback_hlp);
    imapData.setDownloadReport(false);  
  
    MailClient.readMail(http, imapData);

    previousMillis_Check = currentMillis;
    }      
}

I have reduced the output of the readCallback-function like follows

void readCallback_hlp(ReadStatus msg)
{
  Serial.println("INFO: " + msg.info());

  if (msg.status() != "")
    Serial.println("STATUS: " + msg.status());

  if (msg.success())
  {

    for (int i = 0; i < imapData.availableMessages(); i++)
    {
      Serial.println("=================");

      Serial.println("Messsage Number: " + imapData.getNumber(i));
      Serial.println("UID: " + imapData.getUID(i));
      Serial.println("From: " + imapData.getFrom(i));
      Serial.println("Date: " + imapData.getDate(i));
      Serial.println("Subject: " + imapData.getSubject(i));

      if (!imapData.isHeaderOnly())
      {
        Serial.println("Text Message: " + imapData.getTextMessage(i));
        Serial.println("Text Message Charset: " + imapData.getTextMessgaeCharset(i));
        Serial.println("HTML Message: " + imapData.getHTMLMessage(i));
        Serial.println("HTML Message Charset: " + imapData.getHTMLMessgaeCharset(i));
        if (imapData.isFetchMessageFailed(i))
          Serial.println("Fetch Error: " + imapData.getFetchMessageFailedReason(i));

        if (imapData.isDownloadMessageFailed(i))
          Serial.println("Save Content Error: " + imapData.getDownloadMessageFailedReason(i));
      }

      Serial.println();
    }
    
    imapData.empty();
  }
}

**Comment by mobizt** [comment]
Ok thanks I have some question. Why you put the setup of IMAP data object in loop? Do you intend to login different email account?

If you only want to check incoming email, please use only MailClient.readMail(http, imapData); in loop. No need to setup impap data everytime to read email. 

The following code may be in setup or any function that call once.
```C++
imapData.setLogin("imap.gmail.com", 993, "xxxx@gmail.com", "xxxx");
imapData.setFolder("xxxx");
imapData.setFechUID("");
imapData.setSearchCriteria("UID SEARCH ALL");

imapData.setSaveFilePath("/email_data");
imapData.setDownloadAttachment(false);
imapData.setHTMLMessage(true);
imapData.setTextMessage(true);
imapData.saveHTMLMessage(false, false);
imapData.saveTextMessage(false, false);
imapData.setHeaderOnly(true);
imapData.setSearchLimit(20);
imapData.setRecentSort(true);
imapData.setMessageBufferSize(2000);  //200
imapData.setAttachmentSizeLimit(1024 * 1024 * 5);
imapData.setReadCallback(readCallback_hlp);
imapData.setDownloadReport(false);  

```

Leave the following code  in loop
```C++
void vCheck_EMails(void)
{
    if(currentMillis - previousMillis_Check > interval_Check)
    {

        MailClient.readMail(http, imapData);

        previousMillis_Check = currentMillis;
    }      
}

```

Anyway I still want to investigate the abnormal behavior of my library  when imapData object is routinely set in loop.

**Comment by piti1** [comment]
I already tried this before and I tried it again now like you mentioned, but it still does not work. Same error message.

**Comment by mobizt** [comment]
Ok I get the same error too. WiFiClient  cannot start I guess that the memory is not enough (100K up) to start new SSL handshake I need to modify code that allow to free wifi resource and imap data buffer.

Currently imapData.empty() will clear all data and settings.

I will check and let you know soon may be today or tomorrow.

**Comment by mobizt** [comment]
This issue was fixed. Please update the library.
