### ISSUE TITLE
ESP32 cam board with ESP32 mail

### ISSUE THREAD

**Issue by thathardwareguy** [mobizt/ESP32-Mail-Client#23]
Hello, I am trying to send an email with a picture attached to it using the esp32 cam board. The issue now is reading the image from the sdcard. It seems the esp32 cam board supports the SD_MMC library. Kindly help me out with this. Is there any way the SD_MMC library can be used with the ESP32 mail library?

**Comment by mobizt** [comment]
You can use GPIOs which not use by camera to connect SD card.

The SD_MMC library is not necessary as every ESP32 module works with SD library and every SD card.

Edit:
The below connection (taken from [here](https://randomnerdtutorials.com/esp32-cam-video-streaming-face-recognition-arduino-ide/)) is the connection between ESP32 Cam and its built-in SD card adapter (as used in TTGO T8 V1.8 too).

SD Card--->SD Adapter Module--> ESP32 Cam
D0--------->MISO------------------>GPIO 2
CMD------->MOSI------------------>GPIO 15
CLK-------->SCK-------------------->GPIO 14
D3--------->SS---------------------->GPIO 13
GND	------>GND-------------------->GND
VSS------->VSS---------------------->VSS

And config SD card with this function with no need of SD_MMC library
`MailClient.sdBegin(14,2,15,13); //SCK, MISO, MOSI, SS`

Don't use GPIO 2, GPIO 15, GPIO 14 or GPIO 13 which already connected to built-in SD card adapter.  

You can also use Flash or SPIFFS to save and read image.

**Comment by pcbtborges** [comment]
Dear mobizt, thanks a lot for your help.
I am implementing your suggestion and I am facing the following problem:

File file = MailClient.open(path.c_str(), FILE_WRITE); 
and I am getting an error:
'class ESP32_MailClient' has no member named 'open'

#include "SD.h"            // SD Card ESP32
void setup(){
     MailClient.sdBegin(14,2,15,13); //SCK, MISO, MOSI, SS
...
...
}

I am in the process of writing the picture to SD:
File file = MailClient.open(path.c_str(), FILE_WRITE);
file.write(fb->buf, fb->len); // payload (image), payload length

What am I doing wrong?
Thanks in advance
Paulo

**Comment by mobizt** [comment]
```C++
MailClient.sdBegin(14,2,15,13) //Config for ESP32 Cam SD

File file = SD.open("/myPic.jpg", FILE_WRITE);
file.write(fb->buf, fb->len);
file.close();
```

**Comment by pcbtborges** [comment]
Dear mobitz, thanks a lot.
Mail attachment with the picture just taken is working perfect.
Many thanks for your kind assistance.
Paulo
