### ISSUE TITLE
Outlook mail SMTP connection not working

### ISSUE THREAD

**Issue by ryantxu1** [mobizt/ESP32-Mail-Client#24]
Hi, I'm having trouble setting up the smtp connection with outlook. What's strange is that the imap connection works perfectly. I've tried both "smtp.office365.com" and "smtp-mail.outlook.com" as the server name. I appreciate the help!

# Code
`
#include <WiFi.h>
#include <String.h>
#include <HTTPClient.h>
#include "ESP32_MailClient.h"
#include "SPI.h"
#include "Adafruit_GFX.h"
#include "Adafruit_ILI9341.h"

const char* ssid = ssid
const char* password = pass;

SMTPData smtpData;
IMAPData imapData;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);

  WiFi.begin(ssid, password);
  Serial.print("Connecting to Wifi");
  while (WiFi.status() != WL_CONNECTED){}

  Serial.print("IP: ");
  Serial.println(WiFi.localIP());

  smtpData.setLogin("smtp.office365.com", 587, "aaa@outlook.com", "aaa");
  smtpData.setDebug(true);
  smtpData.setSTARTTLS(true);
  smtpData.setSender("Potato", "aaa@outlook.com");
  smtpData.setPriority("High");
  smtpData.setSubject("Subject");
  smtpData.setMessage("Message", false);
  smtpData.addRecipient("bbb@outlook.com");
  if (!MailClient.sendMail(smtpData))
  Serial.println("Error sending Email, " + MailClient.smtpErrorReason());

  //Clear all data from Email object to free memory
  smtpData.empty();

//  imapData.setLogin("outlook.office365.com", 993, "aaa@outlook.com", "aaa");
//  imapData.setDebug(true);
//  imapData.setFolder("Inbox");
//  imapData.setSearchCriteria("UID SEARCH ALL");
//  imapData.setSearchLimit(5); //Only last 5 messages search
//
//  MailClient.readMail(imapData);
//  if (imapData.availableMessages() > 0){
//    for (int i = 0; i < imapData.availableMessages(); i++){
//      Serial.println("UID: " + imapData.getUID(i));
//      Serial.println("ID: " + imapData.getMessageID(i));
//      Serial.println("Subject: " + imapData.getSubject(i));
//
//      String message = imapData.getSubject(i);
//      int index = message.indexOf(';');
//      int index2 = message.indexOf(';', index + 2);
//      String first = message.substring(0,index);
//      String second = message.substring(index+2, index2);
//      String third = message.substring(index2+2);
//
//      Serial.println(first);
//      Serial.println(second);
//
//    }
//}
}

void loop() {
  // put your main code here, to run repeatedly:

}
`

# Error 
`
Connecting to WifiIP: 192.168.43.86
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - smtp-mail.outlook.com
[DEBUG] - 587
[DEBUG] - ERROR: could not connect to server
Error sending Email, could not connect to server
`

**Comment by mobizt** [comment]
Don't use or comment this line `smtpData.setSTARTTLS(true); ` with SMTP port 587.

That port, 587 is already assigned for TLS. 

STARTTLS was for ports for plain text connection e.g. 25 (depending on server implementation) which support TLS.
