### ISSUE TITLE
Does not compile on ESP32

### ISSUE THREAD

**Issue by pcbtborges** [mobizt/ESP32-Mail-Client#27]
Error compiling for ESP32 Dev Module.

**Comment by Bolukan** [comment]
What version, what errors? Did you check the other issue?

**Comment by pcbtborges** [comment]
Arduino IDE 1.8.9
ESP32_Mail_Client-2.0.3
Just says cannot compile for ESP32 DevModule.
If I scroll up the error I see several references to:

`... there are tens of error reports like that:
                                              ^
C:\Users\pctbo\OneDrive\Documents\Arduino\libraries\ESP32_Mail_Client-2.0.3\src\ESP32_MailClient.cpp:1556:49: error: cannot convert 'const __FlashStringHelper*' to 'const char*' for argument '1' to 'void ESP32MailDebugLine(const char*, bool)'

       ESP32MailDebugLine(FPSTR("ERROR: "), false);
                                                 ^
C:\Users\pctbo\OneDrive\Documents\Arduino\libraries\ESP32_Mail_Client-2.0.3\src\ESP32_MailClient.cpp:1570:58: error: cannot convert 'const __FlashStringHelper*' to 'const char*' for argument '1' to 'void ESP32MailDebug(const char*)'

     ESP32MailDebug(FPSTR("INFO: email sent successfully"));
                                                          ^
exit status 1
Erro compilando para a placa ESP32 Wrover Module`

Thanks

**Comment by mobizt** [comment]
Please update the library to version 2.0.4.
The flash string helper error was fixed for latest ESP32 SDK (1.0.3).
