### ISSUE TITLE
MailClient.sendMail fails when called from FreeRTOS Task

### ISSUE THREAD

**Issue by dagwood54** [mobizt/ESP32-Mail-Client#30]
When I call MailClient.sendMail in setup(), everything works fine.

However, when it is called from a FreeRTOS task, there is a memory allocation failure as shown below. My task size allocation is 32768.

Any thoughts? Thanks.

Showing end of log....
[DEBUG] - INFO: send STARTTLS protocol command
[DEBUG] - 220 2.0.0 Ready to start TLS

[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - ERROR: SSL - Memory allocation failed
[DEBUG] - INFO: cleaning SSL connection
[DEBUG] - ERROR: could not connect to server

**Comment by mobizt** [comment]
You are running out of free heap.

You need 100k+ free heap to make mbedTLS to work. 
It's not related to tasks you created.

**Comment by dagwood54** [comment]
Hi,

Any idea how much is needed by the emailer? Can email memory be pre-allocated?

Thanks

Don

—————

**Comment by mobizt** [comment]
No pre-allocate memory for the library, use **ESP.getFreeHeap()** to make sure you have enough free memory before send/receive Email. to make mbedTLS that handles the SSL connection to work.

Are you using PSRAM (external ram)?

**Comment by dagwood54** [comment]
Hi Mobizt,

Yes. Reducing task stack usage took care of the problem. To send a one line plain text email looks like it takes about 97k free heap.

As you reduce available heap, the program responds with a couple of different allocation errors which is fine. At one memory level the program crashes and causes a reboot as apparently it doesn’t quite catch every allocation error. That’s not critical as I added a check prior to calling just as you suggested.

Thanks for your help!

Don
