### ISSUE TITLE
Sending Email memory issues

### ISSUE THREAD

**Issue by lrdmsi** [mobizt/ESP32-Mail-Client#34]
I can use the example program without any issue but when I try to integrate this to send Email notifications, it often fails. I tried the debug option and shows an error near the end of the process.

…
[DEBUG] - INFO: send STARTTLS protocol command
[DEBUG] - 220 2.0.0 SMTP server ready

[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - ERROR: X509 - Allocation of memory failed
[DEBUG] - INFO: cleaning SSL connection
Error, could not connect to server
[DEBUG] - ERROR: could not connect to server
Error sending Email, could not connect to server
Send email test failed

I guess I am wondering how much memory it needs and how to work around the problem.
Thank you

**Comment by mobizt** [comment]
The core library, mbedTLS requires memory approx.. 100k for SSL data encryption/decryption.

If device has not enough free heap more than it required then server connection with SSL/TLS will be failed.

Check your free heap (ESP.getFreeHeap) before send/read Email.

Try to reduce ram usage, reuse the memory, free your dynamic allocation variable.
