### ISSUE TITLE
I have compile error?

### ISSUE THREAD

**Issue by timbuktu031** [mobizt/ESP32-Mail-Client#36]
like this

In file included from D:\arduino\exampls\libraries\ESP32_Mail_Client\src/WiFiClientSecureESP32.h:52:0,

                 from D:\arduino\exampls\libraries\ESP32_Mail_Client\src/ESP32_MailClient.h:36,

                 from D:\arduino\exampls\sketch_nov20a\sketch_nov20a.ino:2:

D:\arduino\exampls\libraries\ESP32_Mail_Client\src/ssl_client32.h:32:30: fatal error: mbedtls/platform.h: No such file or directory

 #include "mbedtls/platform.h"

                              ^

compilation terminated.

exit status 1
보드 LOLIN(WEMOS) D1 R2 & mini 컴파일 에러.

**Comment by mobizt** [comment]
Update your board package (ESP32 Arduino Core SDK) from Boards Manager.

**Comment by timbuktu031** [comment]
ok thank you

**Comment by mobizt** [comment]
This library is for ESP32.
Did you use ESP8266 based module i.e. LOLIN(WEMOS) D1 R2 & mini and try to install the ESP32 library that not support?
