### ISSUE TITLE
Current Date and Time

### ISSUE THREAD

**Issue by BRUCEMACINTYRE** [mobizt/ESP32-Mail-Client#38]
Is it possible to add a getDate getTime function to this library from the WIFI connection or NTP time server.  I would like to do some data loggin in addition to sending out email alerts and I'm not sure how to add data and time stamps to the logging file.

Thank you
Bruce MacIntyre
Brucemacintyre@yahoo.com

**Comment by mobizt** [comment]
Ok I will add this to the library on the next update.

**Comment by mobizt** [comment]
Now date and time functions are available, please update the library.

See the example how to use in Time.ino in examples folder.

**Comment by BRUCEMACINTYRE** [comment]
I just cant let it go.  I just used the new updated library for the date and time function and WOW!  It works really great.  Very nice implementation.  I even powered off my WIFI router while I was running a test and after the router was powered back up the ESP32 reconnected and continued on with my testing.  NEAT!  Thank you so much for providing this update so quickly.  People like you deserve a lot of credit for what you do. Thanks again!  Bruce
