### ISSUE TITLE
LostWifiConnection when sending AP_STA mode

### ISSUE THREAD

**Issue by FrankForsberg** [mobizt/ESP32-Mail-Client#41]
Something happens when I try to email with my application.

Description of the dump is below.

Used libraries in sketch:
#include "HX711.h"
#include <EEPROM.h>
#include <WiFi.h>
#include <AsyncTCP.h>
#include <WiFiClient.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <ESPmDNS.h>
#include "ESPAsyncWebServer.h"
#include <WiFiClientSecure.h>
#include <WebSocketsServer.h>
#include "SPIFFS.h"
#include "FS.h"
#include <SPI.h>
#include <SD.h>
#include <AS5145.h>
#include <Arduino.h>
#include "ESP32_MailClient.h"
#include <Update.h>
#include "time.h"
#define ARDUINOJSON_DECODE_UNICODE 1
#include "ArduinoJson.h"
#include <DropboxManager.h>
#include "web_index.h"

Connecting to SMTP server...
Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x00000000  PS      : 0x00060b30  A0      : 0x800eb9e9  A1      : 0x3ffb10d0
A2      : 0x3ffc1d24  A3      : 0x3ffc2468  A4      : 0x286ea80d  A5      : 0x00000000
A6      : 0x3ffc2468  A7      : 0x00000000  A8      : 0x80188468  A9      : 0x3ffb10b0
A10     : 0x00000000  A11     : 0x00000005  A12     : 0x00000005  A13     : 0x3ffb6190
A14     : 0x3ffd96dc  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x00000014
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000

Backtrace: 0x00000000:0x3ffb10d0 0x400eb9e6:0x3ffb10f0 0x400d7522:0x3ffb1840 0x400f2f89:0x3ffb1fb0 0x40088ddd:0x3ffb1fd0

Decoding stack results
0x400eb9e6: ESP32_MailClient::sendMail(SMTPData&) at /Users/myuser/Documents/Arduino/libraries/ESP32_Mail_Client/src/ESP32_MailClient.cpp line 1016
0x400d7522: loop() at /Users/myuser/Documents/myCode/mailTest.ino line 1113
0x400f2f89: app_main() at /Users/myuser/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/cores/esp32/main.cpp line 26
0x40088ddd: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c line 143

**Comment by mobizt** [comment]
It's a instruction fetch error.

Something wrong in your code.

Somethings are not exist when mcu trying to fetch that instruction.
It's depending on your implementation with your code, be aware of global, local variables.
Make sure the object, struct or variable are initialize and not destroyed or deleted before it use.

And you need to make a separation test for each library before put it all together.

The library is only software and was nothing do with WiFi.
