### ISSUE TITLE
Mail Client Arduino Library for ESP32, version 2.1.1

### ISSUE THREAD

**Issue by dehalo** [mobizt/ESP32-Mail-Client#44]
I constantly get:
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
Connecting to AP......
WiFi connected.
IP address: 
192.168.178.63
Mounting SD Card...
Preparing attach file...
Sending email...
Connecting to SMTP server...
Identification...
Authentication...
Sign in...
Sending Email header...
Error, set recipient failed
Error sending Email, set recipient failed
 
ESP32-CAM (I had to use SD_MMC.h instead of SD.h)
smtpData.addRecipient("dehalo@gmx.net");
smtpData.addCustomMessageHeader("Message-ID: <abcde.fghij1235@gmx.com>");
 
Any ideas?
 
Kind regards
 
Andreas

**Comment by mobizt** [comment]
Invalid recipient, check the recipient email you are trying to send.

This is an error returns from IMAP server when send the recipient setting command.

Follow the example, try to change recipient and sender.

**Comment by mobizt** [comment]
SD_MMC is not supported in this library and it's not neccessary to use.

For ESP32-CAM, you can used SD.h instead, please read this [#23](https://github.com/mobizt/ESP32-Mail-Client/issues/23) for setup.
