### ISSUE TITLE
Sending empty file problems.

### ISSUE THREAD

**Issue by mateusz-kusmierz** [mobizt/ESP32-Mail-Client#45]
Hello. I have trouble while trying to send empty file (0kB).
If I send it alone, it works.
If I attach more attachements, empty files are not sent?

See serial print from esp32 below:
![screen wysylanie maila serial](https://user-images.githubusercontent.com/49459188/72612758-fa11bf00-392d-11ea-8309-392ffa648bba.JPG)

Gmail email-client:
![screen gmail](https://user-images.githubusercontent.com/49459188/72612760-fd0caf80-392d-11ea-859b-a37061f5195d.JPG)

Files we are trying to send are attached to this message.
[scan files.zip](https://github.com/mobizt/ESP32-Mail-Client/files/4076808/scan.files.zip)

Is this normal behaviour?

**Comment by mateusz-kusmierz** [comment]
We found out that this **might** depend of email client, but worth checking.

**Comment by mobizt** [comment]
This is normal for most Email clients.

Outlook and Gmail PC and Web clients don't allow user to attach empty file (zero byte length).

Why do you think it's an issue?
