### ISSUE TITLE
Mail receiving issue : No message content and attachement download error

### ISSUE THREAD

**Issue by SuperOneil** [mobizt/ESP32-Mail-Client#49]
Hi,

I use your library for logging and I don't have any issue with mail sending, it works well (big file in attachement and HTML message). I use an Gmail account.

My issue is regarding the mail receiving by IMAP server. In all cases, I have nothing in the message content (Text or HTML) but no issue with the rest (sender email, subject... all are OK)
If there is an attachement, I can see the description of the file but as soon as I want to download it in the MicroSD card, I have the following message and the ESP32 rebooting :

**[DEBUG] - INFO: connecting to IMAP server...
[DEBUG] - imap.gmail.com
[DEBUG] - 993
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: server connected
[DEBUG] - INFO: send imap command LOGIN
[DEBUG] - * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
[DEBUG] - INFO: send imap command EXAMINE
[DEBUG] - * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
[DEBUG] - INFO: fetch message
[DEBUG] - * 5 FETCH (UID 8 BODY[HEADER.FIELDS (SUBJECT FROM TO DATE Message-ID Accept-Language Content-Language)] {324}
[DEBUG] - * 5 FETCH (UID 8 BODY[1.MIME] {115}
[DEBUG] - * 5 FETCH (UID 8 BODY[1.1.MIME] {95}
[DEBUG] - * 5 FETCH (UID 8 BODY[1.2.MIME] {94}
[DEBUG] - $ NO Some messages could not be FETCHed (Failure)
[DEBUG] - * 5 FETCH (UID 8 BODY[2.MIME] {293}
[DEBUG] - $ NO Some messages could not be FETCHed (Failure)
[DEBUG] - * 5 FETCH (UID 8 BODY[1.1] {2}
[DEBUG] - * 5 FETCH (UID 8 BODY[2] {4620}
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask) 
Core 1 register dump:
PC      : 0x400850dc  PS      : 0x00060036  A0      : 0x3ffb0120  A1      : 0x3ffb0060  
A2      : 0x3ffb8fdc  A3      : 0x3ffda22a  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x3ffda228  A7      : 0x3ffb0254  A8      : 0x00000000  A9      : 0x00000002  
A10     : 0x3ffda22a  A11     : 0x3ffb96fb  A12     : 0x3ffda22c  A13     : 0x00000001  
A14     : 0x00060e23  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x00000001  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x400850dc:0x3ffb0060 0x3ffb011d:0x3ffb0140 0x4012a578:0x3ffb0160 0x4012c7b9:0x3ffb01a0 0x4012d981:0x3ffb0410 0x40147871:0x3ffb0580 0x4000bcc5:0x3ffb05a0 0x4014a1bd:0x3ffb05c0 0x400e3097:0x3ffb05e0 0x400e3123:0x3ffb0610 0x4018a1be:0x3ffb0690 0x400ed731:0x3ffb06b0 0x400f0d8a:0x3ffb1020 0x400d4bb6:0x3ffb1d10 0x400e0c27:0x3ffb1f00 0x400f6999:0x3ffb1fb0 0x4008956d:0x3ffb1fd0

Rebooting...**

Can you help me to solve this issue ?

**Comment by mobizt** [comment]
The stack is overflow.  If you're using the old version which stack size is only 4 kB in loop task , try to update your ESP32 Core SDK (esp32 board package via Board Manager)  https://github.com/espressif/arduino-esp32/releases.

Or you can search the internet for  "esp32 increase stack size"

**Comment by SuperOneil** [comment]
If the download attachment option is disabled, there are no stack error and no rebooting but the message content stay empty and we can read in the debug lines :    

[DEBUG] - * 5 FETCH (UID 8 BODY[1.MIME] {115}
[DEBUG] - * 5 FETCH (UID 8 BODY[1.1.MIME] {95}
[DEBUG] - * 5 FETCH (UID 8 BODY[1.2.MIME] {94}
[DEBUG] - $ NO Some messages could not be FETCHed (Failure)
[DEBUG] - * 5 FETCH (UID 8 BODY[2.MIME] {293}
[DEBUG] - $ NO Some messages could not be FETCHed (Failure)
[DEBUG] - * 5 FETCH (UID 8 BODY[1.1] {2}
[DEBUG] - * 5 FETCH (UID 8 BODY[2] {4620} 

Do you think that it could be relative to the stack size too ?

**Comment by mobizt** [comment]
Yes, the library loop to fech the message header by ID from the server until it returns error (no parts of message with that ID existed). If message contains large multi-part content, it may require more stack memory.

**Comment by SuperOneil** [comment]
Thanks you, I have created a new task with 32Ko stack in order to replace the "loop()" and I can download the attachment without any rebooting.

Have you a way to save the file directly on the MicroSD and not in a folder with the UID of the corresponding mail ? 

But the issue about the message content is not solved. Nothing appears both for HTML or Text message option. My message is quite short : "Test message" written in raw text.

[DEBUG] - INFO: connecting to IMAP server...
[DEBUG] - imap.gmail.com
[DEBUG] - 993
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: server connected
[DEBUG] - INFO: send imap command LOGIN
[DEBUG] - * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
[DEBUG] - INFO: send imap command LIST
[DEBUG] - * LIST (\HasNoChildren) "/" "INBOX"
[DEBUG] - INFO: send imap command EXAMINE
[DEBUG] - * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
[DEBUG] - INFO: search message
[DEBUG] - 
[DEBUG] - INFO: fetch message
[DEBUG] - * 2 FETCH (UID 10 BODY[HEADER.FIELDS (SUBJECT FROM TO DATE Message-ID Accept-Language Content-Language)] {324}
[DEBUG] - INFO: send imap command LOGOUT
[DEBUG] - * BYE LOGOUT Requested
=================
Messsage Number: 11
Messsage UID: 10
Messsage ID: <AM0PR02MB3890969BAED1AD50A782D613AFF90@AM0PR02MB3890.eurprd02.prod.outlook.com>
Accept Language: fr-FR, en-US
Content Language: fr-FR
From: central watts <watts.crd.central@outlook.com>
From Charset: 
To: "watts.crd.group0@gmail.com" <watts.crd.group0@gmail.com>
To Charset: 
CC: 
CC Charset: 
Date: Mon, 16 Mar 2020 09:03:50 +0000
Subject: UPDATE
Subject Charset: 

=================
Messsage Number: 10
Messsage UID: 
Messsage ID: <AM0PR02MB3890969BAED1AD50A782D613AFF90@AM0PR02MB3890.eurprd02.prod.outlook.com>
Accept Language: fr-FR, en-US
Content Language: fr-FR
From: central watts <watts.crd.central@outlook.com>
From Charset: 
To: "watts.crd.group0@gmail.com" <watts.crd.group0@gmail.com>
To Charset: 
CC: 
CC Charset: 
Date: Mon, 16 Mar 2020 09:03:50 +0000
Subject: UPDATE
Subject Charset: 
Text Message: 
Text Message Charset: iso-8859-1
HTML Message: 
HTML Message Charset: 
**************
Attachment: 1 file(s)
File Index: 1
Filename: update.bin
Name: update.bin
Size: 0
Type: application/octet-stream
Creation Date: Mon, 16 Mar 2020 08:55:37 GMT

**Comment by mobizt** [comment]
> Have you a way to save the file directly on the MicroSD and not in a folder with the UID of the corresponding mail ?

No such an option,  you need to check the message and attached files yourself. You can move, rename, delete upon your needs. 

This library is **not intend to work** as in automated system as notification and messaging. Email reading and checking consumed more memory and not suitable in an embedded device.

> But the issue about the message content is not solved. Nothing appears both for HTML or Text message option. My message is quite short : "Test message" written in raw text.

Please try the examples first, read the doc for the options and how to use it.

**Comment by mobizt** [comment]
If you get the sending and receiving attachment errors or even saving the message header and message body to SD errors. The most possible cause is your microSD adapter module or wrong wiring, not properly initialized or locked in write access.

For SD the wiring and initialization, see https://github.com/mobizt/ESP32-Mail-Client/issues/23
