### ISSUE TITLE
Send_Email Project doesn't compile

### ISSUE THREAD

**Issue by FattyBogora** [mobizt/ESP32-Mail-Client#5]
When I try to compile the Send_Email project, I get "HTTPClientESP32Ex.h:37:24: fatal error: HTTPClient.h No such file or directory"

What am I missing?

Thanks!

**Comment by mobizt** [comment]
Please go to [HTTPClientESP32Ex repo](https://github.com/mobizt/HTTPClientESP32Ex) to download the dependency. I also inform this on Readme.

This library has some known bugs in reading email in [this issue](https://github.com/mobizt/ESP32-Mail-Client/issues/2) which I currently try to fix it.

**Comment by FattyBogora** [comment]
You mean:  Firebase-ESP32 and LineNotify-ESP32 libraries?

Or something different...

**Comment by mobizt** [comment]
I mean **this** library (ESP32 Mail Client) has some issue https://github.com/mobizt/ESP32-Mail-Client/issues/2. Nothing refers to Firebase-ESP32 and LineNotify-ESP32??

Please read readme for all info.

**Comment by FattyBogora** [comment]
I have already added this dependency:  Required HTTPClientESP32Ex library to be installed. https://github.com/mobizt/HTTPClientESP32Ex

Anything else I am missing?  The readme doesn't mention any other dependencies...

**Comment by mobizt** [comment]
Thats it let compile. Lets look at comment on the top of each  example sketch for the guide.

Please read document first.

**Comment by FattyBogora** [comment]
Oh well, it still can't find the HTTPClient.h file...  that's too bad, I was hoping to get this to work.

Maybe I'm just dumb :)

**Comment by mobizt** [comment]
Are you new to ESP32?
Did you install esp32 core sdk?

**Comment by mobizt** [comment]
https://github.com/espressif/arduino-esp32

**Comment by FattyBogora** [comment]
Yes, I have made a few ESP32 apps (Sparkfun ESP32 thing)... the version of the SDK I have is from 2017 so I will try and update...

**Comment by FattyBogora** [comment]
Made it farther now... I will keep playing.  Thanks for your time

**Comment by mobizt** [comment]
You're welcome.
