### ISSUE TITLE
cannot send attachments above 64KB

### ISSUE THREAD

**Issue by pabloandresm** [mobizt/ESP32-Mail-Client#52]
for example if you use ".addAttachData("picture.jpg", "image/jpg", (uint8_t *)buf,len);" with the len going over 64K, then the attachment gets truncated.

the parameters all over the library uses uint16_t

it is the case if ::addAttachData() and ::add() and for std::vector<uint16_t>, etc. etc.

**Comment by mobizt** [comment]
Thanks for informing the issue.

Now it fixed already, please update.
