### ISSUE TITLE
ESP32-Mail-Client smtpData.setDebug not recognized

### ISSUE THREAD

**Issue by JohnSchultz44** [mobizt/ESP32-Mail-Client#53]
smtpData.setDebug(true);

setDebug is not recognized by Arduino compiler. Please note that "setDebug" is not in orange like the other methods .setLogin and .setSender

<img width="720" alt="Screen Shot 2020-04-11 at 10 44 27 AM" src="https://user-images.githubusercontent.com/63509149/79048268-8bb56380-7be1-11ea-9f20-bd35b89cdf2c.png">

**Comment by mobizt** [comment]
Ok, due to some tab separation problem in the keyword file.
The fix will be in the future update.
