### ISSUE TITLE
IMAP cannot recognise ethernet connection

### ISSUE THREAD

**Issue by atlantisguru** [mobizt/ESP32-Mail-Client#54]
IMAP cannot recognise the ethernet connection.<br>
_18:22:05.547 -> [DEBUG] - INFO: connecting to IMAP server...
18:22:05.547 -> [DEBUG] - imap.gmail.com
18:22:05.547 -> [DEBUG] - 993
18:22:08.609 -> [DEBUG] - ERROR: could not connect to internet_
<br>
Changing line [119](https://github.com/mobizt/ESP32-Mail-Client/blob/df78d3198c2e4965197288f8391d68c909c0acf7/src/ESP32_MailClient.cpp#L119) in ESP32_MailClient.cpp from this:
`if (WiFi.status() != WL_CONNECTED)`
to this:
`if (WiFi.status() != WL_CONNECTED && !ETH.linkUp())`
solves the problem.

**Comment by mobizt** [comment]
Ok, I will fix it but for ethernet testing, I will create another branch.
