### ISSUE TITLE
IMAP cannot sign in via ethernet

### ISSUE THREAD

**Issue by atlantisguru** [mobizt/ESP32-Mail-Client#55]
When using IMAP with ethernet it cannot pass trough the sign in process.

_18:32:22.789 -> [DEBUG] - INFO: connecting to IMAP server...
18:32:22.789 -> [DEBUG] - imap.gmail.com
18:32:22.789 -> [DEBUG] - 993
18:32:25.831 -> [DEBUG] - INFO: starting socket
18:32:25.831 -> [V][ssl_client32.cpp:86] start_ssl_client(): Free internal heap before TLS 193664
18:32:25.831 -> [V][ssl_client32.cpp:88] start_ssl_client(): Starting socket
18:32:25.878 -> [DEBUG] - INFO: connecting to Server...
18:32:35.101 -> [DEBUG] - INFO: server connected
18:32:35.101 -> [DEBUG] - INFO: seeding the random number generator
18:32:35.154 -> [V][ssl_client32.cpp:157] start_ssl_client(): Seeding the random number generator
18:32:35.154 -> [DEBUG] - INFO: setting up the SSL/TLS structure...
18:32:35.154 -> [V][ssl_client32.cpp:181] start_ssl_client(): Setting up the SSL/TLS structure...
18:32:35.154 -> [I][ssl_client32.cpp:292] start_ssl_client(): WARNING: Use certificates for a more secure communication!
18:32:35.154 -> [V][ssl_client32.cpp:339] start_ssl_client(): Setting hostname for TLS session...
18:32:35.154 -> [DEBUG] - INFO: performing the SSL/TLS handshake...
18:32:35.154 -> [V][ssl_client32.cpp:380] start_ssl_client(): Performing the SSL/TLS handshake...
18:32:37.466 -> [DEBUG] - INFO: verifying peer X.509 certificate...
18:32:37.466 -> [V][ssl_client32.cpp:420] start_ssl_client(): Verifying peer X.509 certificate...
18:32:37.466 -> [V][ssl_client32.cpp:436] start_ssl_client(): Certificate verified.
18:32:37.513 -> [V][ssl_client32.cpp:454] start_ssl_client(): Free internal heap after TLS 153532
18:32:37.513 -> [DEBUG] - INFO: server connected
18:32:38.014 -> [DEBUG] - INFO: send imap command LOGIN
18:32:38.014 -> [V][ssl_client32.cpp:507] send_ssl_data(): Writing HTTP request...
18:32:38.014 -> [V][ssl_client32.cpp:507] send_ssl_data(): Writing HTTP request...
18:32:38.014 -> [V][ssl_client32.cpp:507] send_ssl_data(): Writing HTTP request...
18:32:38.014 -> [V][ssl_client32.cpp:507] send_ssl_data(): Writing HTTP request...
18:32:38.014 -> [V][ssl_client32.cpp:507] send_ssl_data(): Writing HTTP request...
18:32:38.014 -> [DEBUG] - ERROR: could not sigin
18:32:38.014 -> [DEBUG] - INFO: cleaning SSL connection
18:32:38.014 -> [V][ssl_client32.cpp:463] stop_ssl_socket(): Cleaning SSL connection._

Gmail "less secure apps" enabled.
Gmail IMAP option enabled.
Credentials are all OK. (Tested with mail clients)

I can't print out the raw server response by inserting a
`Serial.print(c);`
after line [2384](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L2384) neither with
`ESP32MailDebugInfo(c);`
I've got literally nothing from these lines when the debug shows clearly the server communicates.

The debug shows "Writing HTTP request..." 5 times, but i found only 4 lines of code related to login process started with line [221](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L221).

(Maybe its somehow related to [#48](https://github.com/mobizt/ESP32-Mail-Client/issues/48), because the SMTP fails always on the authentication process, when another library can get trough it.)

What i need to insert and where to print out the raw server responses?

**Comment by mobizt** [comment]
I can't help with this issue because I don't have the ethernet capable board, and the ethernet access is contribute by [velbn](https://github.com/mobizt/ESP32-Mail-Client/commits?author=velbn).

You may set up ETH to be ready and debug its event in the sketch as this example.

https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/ETH_LAN8720/ETH_LAN8720.ino

I think it should work for the lan7810 chip too.

**Comment by mobizt** [comment]
Now the library updated with the WiFi control and WiFi and ethernet status checking removed.

This allows the user to handle WiFi and ethernet connection himself. 

If you still get the ethernet issue, an ethernet chip may not support by the SDK or not properly config or wiring/connection problem.

**Comment by atlantisguru** [comment]
And after the 2.1.4 update just works everything fine.
Thank you!
