### ISSUE TITLE
port 25 usng TLS

### ISSUE THREAD

**Issue by MarcEngrie** [mobizt/ESP32-Mail-Client#57]
Hi, 
I setup my ESP32 using your library for SMTP mail sending. Port is set to 25 and I explicit 'disable' STARTTLS. 

// Set the SMTP Server Email host, port, account and password
  smtpData.setLogin(smtpServer, 25, "", "");

  //For library version 1.2.0 and later the STARTTLS will be enabled automatically
  // when port 587 was used, or enable it manually using setSTARTTLS function.
  smtpData.setSTARTTLS(false);

  smtpData.setDebug(true);

Nevertheless, it starts SSL/TLS. As my smtp server is not configured for that (nor do I want to do this at this time), it fails.

12:04:46.001 -> [DEBUG] - INFO: connecting to SMTP server...
12:04:46.001 -> [DEBUG] - oldies.engrie.local
12:04:46.001 -> [DEBUG] - 25
12:04:46.001 -> [DEBUG] - INFO: starting socket
12:04:46.069 -> [DEBUG] - INFO: connecting to Server...
12:04:46.069 -> [DEBUG] - INFO: server connected
12:04:46.069 -> [DEBUG] - INFO: seeding the random number generator
12:04:46.069 -> [DEBUG] - INFO: setting up the SSL/TLS structure...
12:04:46.069 -> [DEBUG] - INFO: setting hostname for TLS session...
12:04:46.069 -> [DEBUG] - INFO: performing the SSL/TLS handshake...
12:04:46.108 -> [DEBUG] - ERROR: SSL - An invalid SSL record was received
12:04:46.108 -> [DEBUG] - INFO: cleaning SSL connection
12:04:46.108 -> Error, could not connect to server
12:04:46.108 -> [DEBUG] - ERROR: could not connect to server

Is there a way or setting or ... to stop this?

Thx

**Comment by mobizt** [comment]
The library may not support insecure SMTP and IMAP servers.

If you can config the server settings, please choose the secure port instead.

**Comment by mobizt** [comment]
The library was designed to work with secured Email services.
If you intend to use insecure Email service, this library may not suitable to use.

Other Email libraries that depend on HTTPClient library can work in non secure mode and may be your good choise.
