### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cschwarz007** [mobizt/ESP32-Mail-Client#59]
I am using ESP32-Mail-Client with ArduinoIDE 1.8.12.
I used the Board Manager to install the latest  ESP32 Arduino Core SDK (1.0.4), but I am getting the following compile error:
`error: 'mbedtls_ssl_conf_psk' was not declared in this scope`

How can I solve this?

**Comment by mobizt** [comment]
KYour problem is due to an incompleted esp32 board package (ESP32 Arduino Core SDK).

Please try to uninstall and reinstall again.

I test with the latest Arduino IDE 1.8.12 and Arduino Core 1.0.4 and don't see any problem.
