### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by frank2360** [mobizt/ESP32-Mail-Client#60]
Hi,

I think I have the same issue as the previous person. I have installed the latest version for the ESP32 core via the boards manager (version 1.0.4) but I still get an error. I use a Nodemcu ES32 development board from Joy-it.

Here is the full verbose output of the compilation, thanks for looking at it:

Arduino: 1.8.12 (Windows 10), Board: "ESP32 Dev Module, QIO, 80MHz, 4MB (32Mb), 115200, None"

Multiple libraries were found for "SD.h"
 Used: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
Using library ESP32_Mail_Client at version 2.1.4 in folder: C:\Users\frank_000\Documents\Arduino\libraries\ESP32_Mail_Client 
Using library WiFi at version 1.0 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\WiFi 
Using library SD at version 1.0.5 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\SD 
Using library FS at version 1.0 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\FS 
Using library SPI at version 1.0 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\SPI 
Using library SPIFFS at version 1.0 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\SPIFFS 
Using library HTTPClient at version 1.1 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\HTTPClient 
Using library WiFiClientSecure at version 1.0 in folder: C:\Users\frank_000\Documents\Arduino\hardware\espressif\esp32\libraries\WiFiClientSecure 
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by mobizt** [comment]
I see many people don't know what is the actual problem when they're using the third party library that has a header or class name that redundant with the standard name that used in the core library.

Those libraries have different function interfaces and conflict with the core library.

In this case, you need to delete the SD library at **C:\Program Files (x86)\Arduino\libraries\SD** that is not compatible with the core SD library.

**Comment by mobizt** [comment]
Not only SD library, but you also need to delete the WiFi folder at **C:\Program Files (x86)\Arduino\libraries\WiFi**.

**Comment by frank2360** [comment]
Thanks for your prompt answers but after deleting these two folders I still get the error.

Frank

**Comment by mobizt** [comment]
Your ESP32 Arduino Core SDK installation may not complete,

You need to delete the SDK version folder in  **C:\Users\YourName\AppData\Local\Arduino15\packages\esp32\hardware\esp32**, then reinstall it from board managers again.

If you still get the compile errors, try to temporarily remove all libraries in the libraries folder and install this library again.

**Comment by mobizt** [comment]
It's better to post in Github instead of reply to the notifying email to read the updated post and reply.

**Comment by frank2360** [comment]
I deleted all libraries, installed this library again and reloaded the esp32 via board manager again but I still have the same result. What can I test more?

**Comment by mobizt** [comment]
I don't know what is your esp32 board URL (e.g. https://dl.espressif.com/dl/package_esp32_index.json) in the Preferences window (in Arduino IDE).
The problem is somewhere in your installation.

Again, the library tested in the latest Arduino IDE 1.8.12 and esp32 core SDK 1.0.4 and PlatformIO without any issue.

**Comment by frank2360** [comment]
I will try tomorrow with a fresh installation of Arduino on another PC and will keep you posted, thanks already for your help.

**Comment by mobizt** [comment]
Could you change your computer user name to any without the number and white space?

The toolchains use the command-line interface with python which I see some tilde character ( ~ ) in some links to the library that shorten your username as found in ms-dos command.

**Comment by frank2360** [comment]
Hi, I can confirm that it is working on a fresh install on another computer. 
Thanks for your help.
