### ISSUE TITLE
Limiting factor on SPIFFS attachment size?

### ISSUE THREAD

**Issue by stephenf7072** [mobizt/ESP32-Mail-Client#61]
Hi Mobitz,
Thanks for an excellent library, I have been exploring and testing it for use in a larger project.  Not so much an issue as a question: what determines the attachment size from SPIFFS?  I have successfully sent a 750kB .csv attachment from SPIFFS, but 1000kB attachment doesn't work.

Best regards,
Stephen

**Comment by mobizt** [comment]
It depends on SPIFFS partion size settings and some unknown limitation in core library. Did you success to open and read thunks from 1 Mbyte of your own file? You can try it yourself and get the answer.

**Comment by stephenf7072** [comment]
Thanks for the quick reply.  1Mbyte is the biggest file I can get into the SPIFFS on my sample board (4MB flash, with default SPIFFS partition), and 750kbyte is the biggest I can send as an attachment, but perhaps this is related to the partition size rather than the mail client.  

Yes, I can split the file into smaller chunks, I was just curious, and wanted to have something in case others are searching in the future.  I will do some more experiments and reply with the results (perhaps the issue should be left open for a while to give others the opportunity to see and comment).
