### ISSUE TITLE
Compilation error: field 'timeinfo' has incomplete type 'tm'

### ISSUE THREAD

**Issue by Mariusz1** [mobizt/ESP32-Mail-Client#62]
After updating to the recent version (2.1.4) I have the following compilation error:
`C:/users/mariusz/.platformio/lib/ESP32 Mail Client_ID6221/src/ESP32TimeHelper.h:62:13: error: field 'timeinfo' has incomplete type 'tm'
   struct tm timeinfo;`

The full log:
`
In file included from C:/users/mariusz/.platformio/lib/ESP32 Mail Client_ID6221/src/ESP32_MailClient.h:50:0,
                 from src\MyMail.cpp:8:
C:/users/mariusz/.platformio/lib/ESP32 Mail Client_ID6221/src/ESP32TimeHelper.h:62:13: error: field 'timeinfo' has incomplete type 'tm'
   struct tm timeinfo;
             ^
In file included from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\cwchar:44:0,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\bits\postypes.h:40,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\bits\char_traits.h:40,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\string:40,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\random:40,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\bits\stl_algo.h:66,
                 from c:\users\mariusz\.platformio\packages\toolchain-xtensa32\xtensa-esp32-elf\include\c++\5.2.0\algorithm:62,
                 from C:/users/mariusz/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:142,
                 from src\MyMail.cpp:7:
C:/users/mariusz/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/wchar.h:56:8: note: forward declaration of 'struct tm'
 struct tm;
        ^
`

I use Platform IO with all up to date libraries.
Any ideas?

**Comment by mobizt** [comment]
This due to the forward declaration of the **tm** structure in file **C:\Users\mariusz\\.platformio\packages\framework-arduinoespressif32\tools\sdk\include\newlib\wchar.h** which may include by the third-party library which this struct already declared in the ESP32-Mail-Client library.

You need to edit the source of this library, file ESP32TimeHelper.h at line [62](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32TimeHelper.h#L62)


From
`struct tm timeinfo;`
To 
`tm timeinfo;`

**Comment by Mariusz1** [comment]
> This due to the forward declaration of the **tm** structure in file

Thank you for the quick answer, but the problem remains (I also did 'Clean' of the project).

**Comment by mobizt** [comment]
This is the C++ compiler issue that may not configure properly.

The tm structure was already declared in **time.h** and forward declaration in **wchar.h**.

if **time.h** was included in your code or in the library and you get this compilation error, you may need to reinstall the platformIO again.

Try update the toolchains first with **pio update** command, if not work then reinstall the platformIO.

**Comment by Mariusz1** [comment]
Thank again for the quick response. Unfortunately:

- **pio update** did not change anything,
- removing the _.platformio_ folder and reinstalling made it even worse, because I was not able to compile the project due to many strange errors,

I decided to restore my old _.platformio_ folder and downgrade the _ESP32 Mail Client_ library to version 2.0.8. I know it is an ugly workaround.

**Comment by mobizt** [comment]
I mean uninstall platformIO from Atom or VSCode IDE and install it again.

The library developed with the platformIO and test under platformIO and Arduino.
