### ISSUE TITLE
Compile errors using ESP32 Mail Client on VS Code PlatformIO

### ISSUE THREAD

**Issue by ghost** [mobizt/ESP32-Mail-Client#64]
I successfully used your library with a few of your examples, using the standard Arduino IDE, and I had no issues. When I tried to repeat the example using VS Code with the PlatformIO extension, the C++ compiler threw fatal errors on the compile. The PIO community sniffed that the library did not follow true C++ standards, and they said to fix the library. Hate that elitism that I see there. Have you encountered this issue before? Is there a workaround you could suggest? Thanks...

**Comment by mobizt** [comment]
Please post the error.

PIO itself has LDF scanning bug which they don't fix it.

**Comment by mobizt** [comment]
The library developed with PlatformIO on VSCode.

**Comment by ghost** [comment]
Well, I solved this problem by deleting an installed global library in PIO called ArduinoHTTPClient. Note that there is also a Built-In library called HTTPClient for the NodeMCU-32S, according to the PIO library manager. Somehow during the compile and linking process, the Arduino IDE ignored this installed library and the program ran fine, but the same process done with PIO used this library and it failed to compile. I deleted this library in the Arduino IDE, and it still ran fine there, too.

So this is one of the primary reasons motivating me to move over to PIO. Library management in the Arduino IDE is a mess once you have many projects using variants of ESP32s, ESP8266, Arduinos, etc. etc. etc. All of these installed global libraries in PIO seem to have been swept over from what I had installed in the Arduino IDE somehow. Perhaps when I tried to import an existing Arduino project into PIO. Seems like the best path forward with PIO would be for me to uninstall all the global libraries, and reinstall only the ones needed by each project, as project libraries.

Thanks very much for responding so quickly to my post...

**Comment by mobizt** [comment]
That the problems of PIO LDF that all files even some does not used by this library will be included and causes conflicts. Even PIO has some options for LDF but it's not convenient to use by user.

https://docs.platformio.org/en/latest/librarymanager/ldf.html
