### ISSUE TITLE
Random SMTP failure. ERROR: reading incoming data failed!

### ISSUE THREAD

**Issue by thomastech** [mobizt/ESP32-Mail-Client#66]
I am sending email to a Comcast mail server. Randomly the mail fails, perhaps 1 out of 5 attempts. My debugging workaround is to resend it until it is successful, but this is undesirable since it adds more delays to main code execution.

Here is the serial log from a failed email:
```
EMail: Callback Status -> Connecting to SMTP server...
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - smtp.comcast.net
[DEBUG] - 587
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: begin STARTTLS handshake
[DEBUG] - 220 resomta-ch2-11v.sys.comcast.net resomta-ch2-11v.sys.comcast.net ESMTP server ready

[DEBUG] - INFO: send SMTP command extended HELO
[DEBUG] - ERROR: reading incoming data failed!
[DEBUG] - INFO: cleaning SSL connection
EMail: Callback Status -> Error, could not connect to server
[DEBUG] - ERROR: could not connect to server
EMail: Error sending Email, could not connect to server
```

My mail related code looks like this (credentials hidden):
```
smtpData.setDebug(true);
smtpData.setLogin("smtp.comcast.net",587, MAIL_ACCT, MAIL_PW);
smtpData.setSTARTTLS(true);
smtpData.setSender("Sender Name Here", MAIL_SENDER);
smtpData.setPriority("Normal");
smtpData.setSubject("My Subject");
String msg = "<div style=\"font-family:arial,helvetica;color:red;;font-size:14px;\">";
String  msg += "This is a test message.</div>";
smtpData.setMessage(msg, true);
smtpData.addRecipient(MAIL_RCVR);
smtpData.addCustomMessageHeader("Hidden Message");
smtpData.setSendCallback(sendCallback);
bool mailSuccess = MailClient.sendMail(smtpData);
```

I don't see anything unusual when it fails (i.e., no long hangs). Also, l haven't experienced mail sending problems when using this Comcast account with desktop email (Win10/WLM). 

The incoming read failure is the only clue. But I haven't figured out why it is occurring. Troubleshooting advice is appreciated.

- Thomas

**Comment by mobizt** [comment]
Don't compare the mail client on PC which has a plenty of resource with the limited resource device.

This is the error in lwip read function.

Please try to change the buffer size in [file ssl_client32.cpp at line 706](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ssl_client32.cpp#L706) from
**size_t bufLen = 512;**
to
**size_t bufLen = 1024;**

If it still fails, something may not meet the server requirement or bugs in lwip in ESP32.

**Comment by mobizt** [comment]
The comcast email server may has internal issue itself.

Please use other standard SMTP service.

**Comment by thomastech** [comment]
@mobizt, thanks for the advice. Unfortunately increasing bufLen did not solve the problem.

I was originally using another SMTP service with your library, but it failed every time (authentication failed error). So then I switched to the comcast mail server. 

In case you have any troubleshooting ideas, here is the serial log from the original mail server that fails every time:

```
EMail: Callback Status -> Connecting to SMTP server...
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - ssd.serversecureplusplusalekito.net
[DEBUG] - 587
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: begin STARTTLS handshake
[DEBUG] - 220-ssd.serversecureplusplusalekito.net ESMTP Exim 4.93 #2 Wed, 08 Jul 2020 15:31:16 +0000 
220-We do not authorize the use of this system to transport unsolicited,
220 and/or bulk e-mail.

[DEBUG] - INFO: send SMTP command extended HELO
[DEBUG] - 250-ssd.serversecureplusplusalekito.net Hello c-98-208-73-25.hsd1.ca.comcast.net [98.208.73.25]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-AUTH PLAIN LOGIN
250-STARTTLS
250 HELP

[DEBUG] - INFO: send STARTTLS protocol command
[DEBUG] - 220 TLS go ahead

[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: smtp server connected
EMail: Callback Status -> Identification...
[DEBUG] - INFO: send smtp HELO command
[DEBUG] - 250 ssd.serversecureplusplusalekito.net Hello c-98-208-73-25.hsd1.ca.comcast.net [98.208.73.25]

EMail: Callback Status -> Authentication...
[DEBUG] - INFO: send smtp AUTH LOGIN command
[DEBUG] - 503 AUTH command used when not advertised

EMail: Callback Status -> Error, authentication failed
[DEBUG] - ERROR: authentication failed
[DEBUG] - INFO: cleaning SSL connection
EMail: Error sending Email, authentication failed
```
- Thomas

**Comment by mobizt** [comment]
For your case, please try to **use port 465 instead** of 587 and **don't use this command smtpData.setSTARTTLS(true); for port 465**

Some SMTP servers don't support STARTTLS (port 587).

**Comment by thomastech** [comment]
Pardon my mistake, I meant to use port 465 when I generated the error log that was posted. This server requires port 465 with SSL and Clear Text Authentication. Regarding STARTTLS, I've tried both enabled and disabled.

Here is the serial log when using the correct port:
```
EMail: Callback Status -> Connecting to SMTP server...
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - ssd.serversecureplusplusalekito.net
[DEBUG] - 465
[DEBUG] - INFO: cleaning SSL connection
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: smtp server connected
EMail: Callback Status -> SMTP server connected, wait for response...
[DEBUG] - 220-ssd.serversecureplusplusalekito.net ESMTP Exim 4.93 #2 Wed, 08 Jul 2020 16:17:20 +0000

[DEBUG] - 220-We do not authorize the use of this system to transport unsolicited, 

[DEBUG] - 220 and/or bulk e-mail.

EMail: Callback Status -> Identification...
[DEBUG] - INFO: send smtp HELO command
[DEBUG] - 250 ssd.serversecureplusplusalekito.net Hello c-98-208-73-25.hsd1.ca.comcast.net [98.208.73.25]

EMail: Callback Status -> Authentication...
[DEBUG] - INFO: send smtp AUTH LOGIN command
[DEBUG] - 503 AUTH command used when not advertised

EMail: Callback Status -> Error, authentication failed
[DEBUG] - ERROR: authentication failed
[DEBUG] - INFO: cleaning SSL connection
```
- Thomas

**Comment by mobizt** [comment]
The mail server you provided is the Extended SMTP (ESMTP) which require EHLO command instead of HELO command in SMTP.

I will add the ESMTP server support soon.

At this time you can try to edit [ESP32_MailClient.cpp at line 1428](https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L1428) from

**smtpData._net->getStreamPtr()->println(ESP32_MAIL_STR_5);** 
to
**smtpData._net->getStreamPtr()->println(ESP32_MAIL_STR_6);**

**Comment by mobizt** [comment]
I update the library to version 2.1.5 with ESMTP supports. 

Please update the library (via GitHub download).

**Comment by thomastech** [comment]
Thank you! Changing line 1428 in the library solved the connection problem.  And more good news, the random mail sending failure hasn't occurred (yet). 

Unfortunately the received emails are mangled. Rather than html, they are plain text with html tags. This issue does not occur when I use the comcast server.

For example:
```
Sent by Test Unit 1 (ESP32 controller)
Mime-Version: 1.0
Content-Type: multipart/mixed; boundary="{BOUNDARY}"

--{BOUNDARY}
Content-type: text/html; charset="UTF-8"
Content-transfer-encoding: 7bit

<div style="font-family:arial,helvetica;color:red;font-size:18px;">Device has Rebooted!</div><div style="font-family:arial,helvetica;font-size:14px;">Button Count is: 9.<br>Fluid Level is: EMPTY.</div><div style="font-family:arial,helvetica;color:red;;font-size:14px;">Please service NOW.</div>

--{BOUNDARY}--
```

In case it helps, here's the serial log from the new mail service:
```
EMail: Callback Status -> Connecting to SMTP server...
[DEBUG] - INFO: connecting to SMTP server...
[DEBUG] - ssd.serversecureplusplusalekito.net
[DEBUG] - 465
[DEBUG] - INFO: starting socket
[DEBUG] - INFO: connecting to Server...
[DEBUG] - INFO: server connected
[DEBUG] - INFO: seeding the random number generator
[DEBUG] - INFO: setting up the SSL/TLS structure...
[DEBUG] - INFO: setting hostname for TLS session...
[DEBUG] - INFO: performing the SSL/TLS handshake...
[DEBUG] - INFO: verifying peer X.509 certificate...
[DEBUG] - INFO: certificate verified
[DEBUG] - INFO: smtp server connected
EMail: Callback Status -> SMTP server connected, wait for response...
[DEBUG] - 220-ssd.serversecureplusplusalekito.net ESMTP Exim 4.93 #2 Wed, 08 Jul 2020 16:47:11 +0000 

[DEBUG] - 220-We do not authorize the use of this system to transport unsolicited,

[DEBUG] - 220 and/or bulk e-mail.

EMail: Callback Status -> Identification...
[DEBUG] - INFO: send smtp HELO command
[DEBUG] - 250-ssd.serversecureplusplusalekito.net Hello c-98-208-73-25.hsd1.ca.comcast.net [98.208.73.25]

[DEBUG] - 250-SIZE 52428800

[DEBUG] - 250-8BITMIME

[DEBUG] - 250-PIPELINING

[DEBUG] - 250-AUTH PLAIN LOGIN

[DEBUG] - 250 HELP

EMail: Callback Status -> Authentication...
[DEBUG] - INFO: send smtp AUTH LOGIN command
[DEBUG] - 334 VXNlcm5hbWU6

EMail: Callback Status -> Sign in...
[DEBUG] - INFO: log in with username and password
[DEBUG] - 334 UGFzc3dvcmQ6

[DEBUG] - 235 Authentication succeeded

EMail: Callback Status -> Sending Email header...
[DEBUG] - INFO: send email header
[DEBUG] - 250 OK

[DEBUG] - 250 Accepted

EMail: Callback Status -> Sending Email body...
[DEBUG] - INFO: send email body
[DEBUG] - 354 Enter message, ending with "." on a line by itself

[DEBUG] - INFO: finalize...
EMail: Callback Status -> Finalize...
[DEBUG] - 250 OK id=1jtDDz-004mu7-Kc

EMail: Callback Status -> Finished
Email sent successfully
Email: Callback Status -> Success
[DEBUG] - INFO: email sent successfully
[DEBUG] - INFO: cleaning SSL connection
```
- Thomas

**Comment by mobizt** [comment]
Strange and should and must not happen. Server should accept multipart MIME message body instead of translate to text.

Try to upload code again.

**Comment by thomastech** [comment]
Thanks for staying with me, I appreciate the help. I've installed the latest library and rebuilt the project. The html encoding is still received as plain text.

- Thomas

**Comment by mobizt** [comment]
Your code here should not be compiled and should error

```C++
String msg = "<div style=\"font-family:arial,helvetica;color:red;;font-size:14px;\">";
String  msg += "This is a test message.</div>";
```
Please try to create the full html document which contains html, header, body tags.

The library works well for most standard servers e.g. outlook, gmail and popular mail services.

If you still get the strange message, the smtp server may not comply to the rfc standard.

**Comment by thomastech** [comment]
Sorry for the distraction. The code typo (duplicate String declaration) was not in my source, just in the posted example. 

I changed the email to use a full html doc with all expected tags. The problem persists. 

Here's the html (please pardon the ugly formatting):

`<!DOCTYPE html><html><head><style>body {background-color: white;text-align: center;color: black;font-family: Arial, Helvetica, sans-serif;}</style></head><body><div style="font-family:arial,helvetica;color:red;font-size:18px;">Device has Rebooted!</div><div style="font-family:arial,helvetica;font-size:14px;">Reboot Count is: 9.<br>Fluid Level is: EMPTY.</div><div style="font-family:arial,helvetica;color:red;;font-size:14px;">Please refill NOW.</div></body></html>`

This same hosting service has other host accounts that I use (all on different servers). I tried them and they too are converting the ESP32 emails to plain text. 

- Thomas

**Comment by mobizt** [comment]
You should update ESP32 Arduino SDK and the library.

This issue should not existed from me and all users that have been used.

Please use standard SMTP servers.

**Comment by thomastech** [comment]
Platformio reports that I'm using the latest ESP32 Platform and Arduino libraries. So this issue must be unique to the mail servers I'm using. 

I'll spend more time with the code; Maybe with luck I will find a solution. In the meantime I've reverted back to the less reliable comcast mail server.

- Thomas

**Comment by thomastech** [comment]
Update: I found a workaround. It seems that _smtpData.addCustomMessageHeader()_ breaks the html messages on the affected servers. 

I've removed that function and now the emails are received with correct html formatting. Glad it was this easy.

Thanks again for providing the ESMTP update.

- Thomas
