### ISSUE TITLE
email header, display ????, UTF-8 no BOM used

### ISSUE THREAD

**Issue by xiaolaba** [mobizt/ESP32-Mail-Client#67]
hello,
single same email message, and the subject, English display was perfect. However once set strings to uses Local char and source code saved format is UTF-8 No-BOM, email subject display on the iphone with "??????", at the same incident, login to gmail web client, its display is correct & readable. About this displaying flaw, mail client issue or need to setup something on email sending? thx.

**Comment by mobizt** [comment]
The none-ASCII text in message header will be decoded using [RFC2047](https://tools.ietf.org/html/rfc2047).

The UTF8 and other decoding  are currently not support.
