### ISSUE TITLE
static IP configuration --> Error, could not connect to server

### ISSUE THREAD

**Issue by lunamera** [mobizt/ESP32-Mail-Client#69]
I'm getting the following in case of a static IP configuration:

> Connecting to SMTP server...
> Error, could not connect to server
> Error sending Email, could not connect to server

The only change between a working and the non-working code is the call to WiFi.config(....)
` if (!WiFi.config(STATIC_IP, SUBNET, GATEWAY,primaryDNS)) {
    Serial.println("STA Failed to configure");
 }`

When I omit this call, the email gets send.
I dumped all IPs, both configurations are showing up the same IP, especially for DNS.
And free heap is also more than 200k in both cases. 

Any ideas?

**Comment by mobizt** [comment]
You need to config the right network configuration.
Library does nothing with your network config.
