### ISSUE TITLE
Changes required to make Dovecot IMAP receive work

### ISSUE THREAD

**Issue by zarya** [mobizt/ESP32-Mail-Client#7]
```
diff --git a/src/ESP32_MailClient.h b/src/ESP32_MailClient.h
index c492af1..fed8bc8 100644
--- a/src/ESP32_MailClient.h
+++ b/src/ESP32_MailClient.h
@@ -211,7 +211,7 @@ static const char ESP32_MAIL_STR_130[] PROGMEM = "$ LOGIN ";
 static const char ESP32_MAIL_STR_131[] PROGMEM = " ";
 static const char ESP32_MAIL_STR_132[] PROGMEM = " OK ";
 static const char ESP32_MAIL_STR_133[] PROGMEM = "$ LIST \"\" \"*\"";
-static const char ESP32_MAIL_STR_134[] PROGMEM = "Success";
+static const char ESP32_MAIL_STR_134[] PROGMEM = "completed";
 static const char ESP32_MAIL_STR_135[] PROGMEM = "$ EXAMINE \"";
 static const char ESP32_MAIL_STR_136[] PROGMEM = "\"";
 static const char ESP32_MAIL_STR_137[] PROGMEM = "UID ";
@@ -222,7 +222,7 @@ static const char ESP32_MAIL_STR_141[] PROGMEM = "SEARCH";
 static const char ESP32_MAIL_STR_142[] PROGMEM = "$ UID FETCH ";
 static const char ESP32_MAIL_STR_143[] PROGMEM = "$ FETCH ";
 static const char ESP32_MAIL_STR_144[] PROGMEM = " BODY.PEEK[HEADER.FIELDS (SUBJECT FROM TO DATE Message-ID Accept-Language Content-Language)]";
-static const char ESP32_MAIL_STR_145[] PROGMEM = "$ OK Success";
+static const char ESP32_MAIL_STR_145[] PROGMEM = "$ OK Fetch completed";
 static const char ESP32_MAIL_STR_146[] PROGMEM = "$ LOGOUT";
 static const char ESP32_MAIL_STR_147[] PROGMEM = " BODY.PEEK[";
 static const char ESP32_MAIL_STR_148[] PROGMEM = ".MIME]";
@@ -1616,4 +1616,4 @@ private:
 
 extern ESP32_MailClient MailClient;
 
-#endif
\ No newline at end of file
+#endif
```

**Comment by mobizt** [comment]
You can pull request which I can check and merge it

**Comment by zarya** [comment]
If i would make a pull request that would break support for Google. After these changes it does not work anymore with Google it will only work (as far as i tested) with Dovecot imap servers.

**Comment by mobizt** [comment]
Thanks for your information and I will make the option to choose GMail and Dovecot in the next update.

**Comment by mobizt** [comment]
I add support Dovecot IMAP server based on your suggestion in [version 1.05](https://github.com/mobizt/ESP32-Mail-Client/releases/tag/1.0.5) already.

**Comment by OersHunorDetre** [comment]
I am getting "Error, could not handle IMAP server response" for gmail. IMAP is enabled on the account. Is it possible that 1.05 update mage the google IMAP handling wrong?

**Comment by OersHunorDetre** [comment]
No. With 1.04 I am getting the same error.

**Comment by mobizt** [comment]
From serial monitor...
Where is the error stop on STATUS debug message i.e. during  initialize, signin, listing?

Make sure you have more than 100k free Heap before send/receive Email otherwise SSL client will fail to connnect.

If error occurred during initialize please try to connect the device with the strong WiFi network.
If error still existed, please try to update ESP32 Arduino Core SDK.

**Comment by OersHunorDetre** [comment]
answered in the newly opened issue
