### ISSUE TITLE
proposal for improvement

### ISSUE THREAD

**Issue by lunamera** [mobizt/ESP32-Mail-Client#70]
You've added date/time functionality to the email lib. That's nice!

But would it be possible to add a function to generate an RFC1123 compliant date to put it into the mail header?

`sprintf (datestr, "Date: %s, %d %s %d %02d:%02d:%02d +0200 (CEST)",
           DAY_NAMES[MailClient.Time.getDayOfWeek()],
           MailClient.Time.getDay(),
           MONTH_NAMES[MailClient.Time.getMonth() - 1],
           MailClient.Time.getYear(),
           MailClient.Time.getHour(),
           MailClient.Time.getMin(),
           MailClient.Time.getSec());
           `

**Comment by mobizt** [comment]
The library is aim for Email sending and receiving. 
There is a [time library](https://github.com/ropg/ezTime) in GitHub that can do this already and it support RFC1123 time format too.
