### ISSUE TITLE
compile error: 'SMTPData' does not name a type

### ISSUE THREAD

**Issue by teppeparsons** [mobizt/ESP32-Mail-Client#72]
When I try to verify/compile an sketch, I get the following error:
'SMTPData' does not name a type

Here's an excerpt of the code I'm using:
#include "ESP32_MailClient.h"
//The Email Sending data object contains config and data to send
SMTPData smtpData;

I'm using Arduino version 1.8.13.  I've tried a couple different example sketches, including the Send_email example.  It always gets hung up on the same line:  SMTPData smtpdata; 

Do I have to define the data type for smtpdata?

thx,
Tom

**Comment by mobizt** [comment]
There are multiple errors from compiler which may show one of you noted here.

There are may causes for the compilation errors as the following.

- You may select the incompatible board from Arduino IDE. This library is for Espressif ESP32 device only.
- You may not properly add the ESP32 board package.json url in the Arduino's Preferences config window.
- You may not install the ESP32 Core SDK for Arduino correctly or not yet installed.
- Your Arduino IDE may not install properly.
- The ESP32-Mail-Client library may not install properly. The problems can be invalid sketch book location (libraries folder) which may locked or can't access by Arduino IDE toolchains executable programs or the library installation problem.

**Comment by hasechris** [comment]
@mobizt 
Hello there,

i also encountered this issue. Setup is as following:
- Archlinux
- VSCode in Open Source Version (aka "Code" in Archlinux)
- PlatformIO
- Installed your Library via PlatformIO
- Copied the first two lines for Email sending

Error:
```
src/main.cpp:18:1: error: 'smtpData' does not name a type
 smtpData.setLogin("smtp.gmail.com", 587, "mara.chrishase@gmail.com", "TelZombi");
 ^
Compiling .pio/build/nodemcu-32s/liba29/SD/SD.cpp.o
```

Code
```
#include <Arduino.h>
#include <OneWire.h>
#include <DallasTemperature.h>
#include <OneWire.h>
#include <ESP32_MailClient.h>

// GPIO where the DS18B20 is connected to
const int oneWireBus = 22;     
// Setup a oneWire instance to communicate with any OneWire devices
OneWire oneWire(oneWireBus);
// Pass our oneWire reference to Dallas Temperature sensor 
DallasTemperature sensors(&oneWire);

//2. For sending Email, declare Email Sending data object in global scope.
SMTPData smtpData;
//3 Setup SMTP server login credential in setup()
smtpData.setLogin("smtp.gmail.com", 587, "blub@bla", "nice passwort");

void setup() {
   // Start the Serial Monitor
  Serial.begin(115200);
  // Start the DS18B20 sensor
  sensors.begin();
}

void loop() {
  sensors.requestTemperatures(); 
  float temperatureC = sensors.getTempCByIndex(0);
  Serial.print(temperatureC);
  Serial.println("ºC");
  delay(1000);
}

```

**Comment by hasechris** [comment]
Nevermind,

i didnt read enough. Your Comment states "//3 Setup SMTP server login credential in setup()"
The Part "in setup()" was lost on my side.

Sorry

**Comment by teppeparsons** [comment]
Thanks for trying to help.  I’ll look through your suggestions later this evening.  The error is very frustrating.   I’m surprised I don’t see more info on the forums about it.  Still trying to solve it.  

-Tom

**Comment by mobizt** [comment]
@teppeparsons I wonder that you don't provide any more feedback.

You can post the whole error message here instead.  The most error is the installation of third party libraries which their class names or file names are the same as in Arduino core library e.g. SD.h which it's functions are not compatible with the core library and the compiler may confuse to choose the suitable one.  For this case, you need to uninstall the libraries especially SD from libraries folder.
