### ISSUE TITLE
IMAP: email body visible only when Charset = utf-8

### ISSUE THREAD

**Issue by tibochina** [mobizt/ESP32-Mail-Client#76]
Hello mobizt, thank you very much for your amazing job.

With IMAP I can receive emails and show the content of these emails if they are encoded in utf-8, but the body text message of emails that were sent as plain text do not appear in the serial monitor.

To illustrate:
If the email was sent as plain texts. The serial monitor shows:
Text Message:                             (Empty)
Text message Charest:              (Empty)

But if the email was sent with **bold** letters and underlined letters etc (or html emails), the serial monitor shows:
Text Message: Bla-bla-bla the text message appears here...
Text message Charest: utf-8

As a side note I use an outlook.com mailbox.
Also the program includes these commands:
imapData.setTextMessage(true)
imapData.saveTextMessage(true, true)

How can do to retrieve the body of emails that were sent as plain text ?
Or in other words, how can I retrieve the email body when Charest is not utf-8?

I suppose I am missing something somewhere, this is so basic that I am pretty sure that this is not a bug from your program. Could it be a problem with outlook mailbox? Or am I missing a command somewhere?

Thank you in advance to give me some help with this.

**Comment by mobizt** [comment]
This is due to the single part body message is not implement. 
The current version of library supports multi-part body. I currently add this feature in the next update.

**Comment by tibochina** [comment]
I see, thank you very much for answering so fast!
I am looking forward for the next update.
You are doing an amazing job!
Thanks

**Comment by mobizt** [comment]
The new library is available here
https://github.com/mobizt/ESP-Mail-Client

Unfortunately the code from the old library (this repository) is not compatible with the new library.

If you interested please see the examples for the usage which its more easier to use and upgrade.

I set this repository will set to obsoleted and no further updates.
