### ISSUE TITLE
readMail: Additional space character in subject line of mails

### ISSUE THREAD

**Issue by Shrill-Girl** [mobizt/ESP32-Mail-Client#79]
When having a longer subject line (i.e. > 55 chars) in a mail I read with "MailClient.readMail( imapData )" I get one additional space character embedded into the subject line when using "imapData.getSubject( n )". The additional space character is around position 50 (51 or 52). I checked the mails source code: the extra space is not in the original mail.

**Comment by mobizt** [comment]
Space at the end of subject or in between of the other the characters?

I almost finish the working on creating the whole new ESP Mail Client library that add support esp8266 and many bugs fixed and features added included the character decoding, please stay tune.
