### ISSUE TITLE
attachmentData _index not initiated/freed

### ISSUE THREAD

**Issue by OersHunorDetre** [mobizt/ESP32-Mail-Client#8]
The smtpData._attach._index is 2 if you send the second email after successfully sending one. This is because smtpData.empty();, therefore clearAttachment(); does not reset the _index. I do not know which one is better, to init _index = 0, or zero it when you free it. I did the second one.

**Comment by mobizt** [comment]
Thanks for addressing the issue. I update and fixed in [version 1.05](https://github.com/mobizt/ESP32-Mail-Client/releases/tag/1.0.5) already.
