### ISSUE TITLE
can you adapt this to Arduino MKR boards?

### ISSUE THREAD

**Issue by gratefulfrog** [mobizt/ESP32-Mail-Client#80]
Hi!

Thank you for the GREAT LIBRARY !!!

Sorry to make an issue, but I saw no other way of contacting you.

Is it imaginable to port this library to the Arduino MKR series of boards, eg MKR WIFI 1010 ?

Any thoughts would be great!
Cheers,
Bob

**Comment by mobizt** [comment]
Thanks for interesting. 

I think it's possible, it has some smaller memory size as compared to ESP8266 and I will try to port later after I finish the update of new ESP-Mail-Client library.
