### ISSUE TITLE
OR condition in setSearchCriteria

### ISSUE THREAD

**Issue by luigimarmo** [mobizt/ESP32-Mail-Client#82]
Hi, 
I'm trying to do OR condition in setSearchCriteria.
I already tried with:
imapData.setSearchCriteria("UID SEARCH FROM \"email1@example.com\" OR FROM \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH FROM \"email1@example.com\" OR FROM \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH FROM \"email1@example.com\" OR \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH FROM (\"email1@example.com\" OR \"email2@example.com\")");

imapData.setSearchCriteria("UID SEARCH ALL FROM \"email1@example.com\" OR FROM \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH ALL FROM \"email1@example.com\" OR FROM \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH ALL FROM \"email1@example.com\" OR \"email2@example.com\"");
imapData.setSearchCriteria("UID SEARCH ALL FROM (\"email1@example.com\" OR \"email2@example.com\")");

imapData.setSearchCriteria("UID SEARCH FROM email1@example.com OR FROM email2@example.com");
imapData.setSearchCriteria("UID SEARCH FROM email1@example.com OR FROM email2@example.com");
imapData.setSearchCriteria("UID SEARCH FROM email1@example.com OR email2@example.com");
imapData.setSearchCriteria("UID SEARCH FROM (email1@example.com OR email2@example.com)");

imapData.setSearchCriteria("UID SEARCH ALL FROM email1@example.com OR FROM email2@example.com");
imapData.setSearchCriteria("UID SEARCH ALL FROM email1@example.com OR FROM email2@example.com");
imapData.setSearchCriteria("UID SEARCH ALL FROM email1@example.com OR email2@example.com");
imapData.setSearchCriteria("UID SEARCH ALL FROM (email1@example.com OR email2@example.com)");

but no luck!
Is there a bug in OR condition?

Thanks

**Comment by mobizt** [comment]
Edit: remove some confused comment.

As stated in the README, the library is deprecated and no further update and bugs fix and the support related to these issues may be discarded.

The new library is available here https://github.com/mobizt/ESP-Mail-Client
