### ISSUE TITLE
Error, could not handle IMAP server response 

### ISSUE THREAD

**Issue by OersHunorDetre** [mobizt/ESP32-Mail-Client#9]
With the example Receive_email I am getting the following error below with gmail. I have enabled the IMAP in the gmail settings and non safe apps. Anything else I have to setup on my account? I tried another account, but getting the same error on gmail. I tried a non gmail account and works, but stuck at listing directories.  (btw, typo: "Lising folders...")

Gmail:
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
267820

My university server:
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Sign in...
STATUS: signin
INFO: Lising folders...
STATUS: listing

**Comment by mobizt** [comment]
With GMAL for your case, I need to investigate what's the response from server which not match the expected OK response.

At line 1694
https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L1694
Add  `Serial.println("############");`

At line 1703 
https://github.com/mobizt/ESP32-Mail-Client/blob/master/src/ESP32_MailClient.cpp#L1703
Add `Serial.print(c);`

Copy all serial monitor text for GMail and other IMAP.

**Comment by OersHunorDetre** [comment]
The gmail response (seems to be no response):

INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
############
INFO: Error, could not handle IMAP server response
STATUS: failed
267968

**Comment by OersHunorDetre** [comment]
The university server response ends with a sort of never ending chars:

INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
############
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN SASL-IR] mailbox1.caesar.elte.hu Cyrus IMAP git2.4.17+0-Debian-2.4.17+nocaldav-0+deb8u2+iig1 server ready
INFO: Sign in...
STATUS: signin
############
$ OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxte QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SORT SORT=MODSEQ SORT=DISPLAY THREAD=ORDEREDSUBJECT THREAD=REFERENCES ANNOTATEMORE LIST-EXTENDED WITHIN QRESYNC SCAN XLIST URLAUTH URLAUTH=BINARY LOGINDISABLED AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN COMPRESS=DEFLATE IDLE] User logged in SESSIONID=<cyrus-1737-1557219884-1>
INFO: Lising folders...
STATUS: listing
############
$ OK Completed (0.058 secs)
????????????????????????????????????????????????????? (<-special chars never end)

**Comment by OersHunorDetre** [comment]
Some more info:
1. What I copied is just after the reset and wifi login, using your Receive_mail.ino example.
2. After "failed" that is the heap printed out, 267968 bites.
3. The internet is a 100mbit/s one, the response time of google.com is ~20ms.
4. The arduino is up to date, so should be the ESP32 Arduino Core SDK.

**Comment by mobizt** [comment]
Try ESP32 Arduino Core SDK v1.01 or higher in Boards Manager.

**Comment by OersHunorDetre** [comment]
esp32 by Espressif Systems version 1.0.2 INSTALLED

**Comment by OersHunorDetre** [comment]
I can send emails using your example. Receiving does not work on any of my accounts. In my google settings: "Status: IMAP is enabled", "Less secure app access: On". Anything else I overlooked?

**Comment by zarya** [comment]
This is Cyrus IMAP a good chance is that the lib will not work since commands returned by Cyrus are different. I run in to the exact same issues with Dovecot.

Only way to fix this is find out what changes need to be make to make the lib read the responses correctly.

**Comment by zarya** [comment]
I expect changes need to be made to:
I expect looking at your logs you need to change this to "Completed" for it to work since these strings are case sensitive.

static const char ESP32_MAIL_STR_134[] PROGMEM = "Completed";

I cant see what this one should be from the logs provided.
static const char ESP32_MAIL_STR_145[] PROGMEM = "$ OK Fetch completed";

**Comment by mobizt** [comment]
Thanks zarya for your information which help me to improve the library.

For GMail I don't know the reason why the IMAP never reply anything should be something wrong.

For Cyrus, it should list the mailbox folders as states in http://www.networksorcery.com/enp/rfc/rfc3501.txt on page 42 and should not return OK responses before * LIST.

The possibility of the error I think now is the Cyrus server replies the $ OK Completed of last command  (LOGIN) too delay and my code begins send LIST command too early, this may need to clear the rx buffer and wait, before issue the next command.

I need to fix this and let you know later.

**Comment by OersHunorDetre** [comment]
I tried again with the Cyrus server. After Zarya's suggstion I modified  ESP32_MAIL_STR_134[] PROGMEM = "Completed";
It goes further now, but stops with "NO Mailbox does not exist" error. No message folders?

INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
############
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN SASL-IR] mailbox1.caesar.elte.hu Cyrus IMAP git2.4.17+0-Debian-2.4.17+nocaldav-0+deb8u2+iig1 server ready
INFO: Sign in...
STATUS: signin
############
$ OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxte QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SORT SORT=MODSEQ SORT=DISPLAY THREAD=ORDEREDSUBJECT THREAD=REFERENCES ANNOTATEMORE LIST-EXTENDED WITHIN QRESYNC SCAN XLIST URLAUTH URLAUTH=BINARY LOGINDISABLED AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN COMPRESS=DEFLATE IDLE] User logged in SESSIONID=<cyrus-25655-1557749176-1>
INFO: Lising folders...
STATUS: listing
############
$ OK Completed (0.078 secs)
INFO: :::::::Message folders:::::::
STATUS: listing
INFO: Reading INBOX folder...
############
$ NO Mailbox does not exist
INFO: Error, could not parse command
STATUS: failed

**Comment by OersHunorDetre** [comment]
My login setup:
imapData.setLogin("myname.mailbox.elte.hu", 993, myname@elte.hu, mypassw);

What I am not sure if it is faulty, but once it appears in the server's answer: "mailbox1.caesar.elte.hu". Shouldn't be that "myname.mailbox.elte.hu"?

**Comment by OersHunorDetre** [comment]
I am not sure if this is helping:
https://github.com/cyrusimap/cyrus-imapd/issues/2569

**Comment by mobizt** [comment]
@OersHunorDetre 

File ESP32_MailClient.h at line 212 please try to change to
```C++
//Old
static const char ESP32_MAIL_STR_133[] PROGMEM = "$ LIST \"\" \"*\"";

//New
static const char ESP32_MAIL_STR_133[] PROGMEM = "$ LIST \"\" \"\"";
```

**Comment by mobizt** [comment]
From your last post, I found that, Cyrus replies **OK** twices after login while Gmail doesn't. 

First at **OK [CAPABILITY IMAP4rev1 LITER...** and the second at **$ OK Completed (0.078 secs)**

Code in  ESP32_MailClient.cpp at line 196 which expected  the server response **ESP32_MAIL_STR_132** or **OK** then the first response i.e. **OK [CAPABILITY IMAP4rev1 LITER...** causes  it to exit the function **waitIMAPResponse** immediately without waiting for  **$ OK Completed**

After exit **waitIMAPResponse** too early and causes my library continue to send IMAP command **ESP32_MAIL_STR_133** to list folder when Cyrus server is not ready (becasuse it not yet finish the response) to accept the next client request.

Now in ESP32_MailClient.cpp at line 196 please try to change

```C++
//Old
if (!waitIMAPResponse(http, imapData, cbData, IMAP_COMMAND_TYPE::LOGIN, ESP32_MAIL_STR_132))

//New
if (!waitIMAPResponse(http, imapData, cbData, IMAP_COMMAND_TYPE::LOGIN, "$ OK Completed"))

```

**Comment by OersHunorDetre** [comment]
After the 2 mods (both .h and .cpp) the serial response:

WiFi connected.
IP address: 192.168.0.21

INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
############
* OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN SASL-IR] mailbox1.caesar.elte.hu Cyrus IMAP git2.4.17+0-Debian-2.4.17+nocaldav-0+deb8u2+iig1 server ready
INFO: Sign in...
STATUS: signin
############
$ OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxte QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SORT SORT=MODSEQ SORT=DISPLAY THREAD=ORDEREDSUBJECT THREAD=REFERENCES ANNOTATEMORE LIST-EXTENDED WITHIN QRESYNC SCAN XLIST URLAUTH URLAUTH=BINARY LOGINDISABLED AUTH=GSSAPI AUTH=PLAIN AUTH=LOGIN COMPRESS=DEFLATE IDLE] User logged in SESSIONID=<cyrus-4242-1557762140-1>
???????????????????????????????????????????? (...neverending)

**Comment by MikeGaby** [comment]
I have the same problem to get my strato emails

INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
275516

Read Email...
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
274496

Read Email...
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
273492

Read Email...
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed
INFO: Connecting to IMAP server...
STATUS: initialize
INFO: IMAP server connected, wait for response...
STATUS: wait_for_response
INFO: Error, could not handle IMAP server response
STATUS: failed

**Comment by mobizt** [comment]
Hi everyone, 

Now I update the library to v1.1.0 which fixed many issues from known servers included for strato.de, Outlook, Dovecot and also Cyrus.

Actually Cyrus server does not comply to rfc3501 as it resonses CAPABILITY response without any CAPABILITY request after LOGIN command, hope this library update will be fixed the issue.

I cannot setup mail server or sign up email services for anyone to test, create test account for me from your being used mail servers or services will help me to test and investigate the issues.
